/*
*    ARRAY FORMAT:
*        0: STRING (Classname)
*        1: STRING (Display Name, leave as "" for default)
*        2: SCALAR (Price)
*        3: STRING (Conditions) - Must return boolean :
*            String can contain any amount of conditions, aslong as the entire
*            string returns a boolean. This allows you to check any levels, licenses etc,
*            in any combination. For example:
*                "call life_coplevel && license_civ_someLicense"
*            This will also let you call any other function.
*
*   Clothing classnames can be found here: https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Equipment
*   Backpacks/remaining classnames can be found here (TIP: Search page for "pack"): https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY
*
*/
class Clothing {
      class CID {
          title = "STR_Shops_CID_Cloth";
          conditions = "call life_coplevel >= 7";
          side = "cop";
          uniforms[] = {
              { "NONE", $STR_C_Remove_uniforms, 0, "" },
              { "travis_polocookiemonster", "", 500, { "", "", -1 } },
              { "travis_polosecurity", "", 500, { "", "", -1 } },
              { "travis_poloapple", "", 500, { "", "", -1 } },
              { "travis_polohellokitty", "", 500, { "", "", -1 } },
              { "travis_polohellokitty1", "", 500, { "", "", -1 } },
              { "travis_timmac", "", 500, { "", "", -1 } },
              { "travis_Butts", "", 500, { "", "", -1 } },
              { "travis_poloaustralia", "", 500, { "", "", -1 } },
              { "travis_polospongebob", "", 500, { "", "", -1 } },
              { "travis_polopatrickstar", "", 500, { "", "", -1 } },
              { "travis_polocanda", "", 500, { "", "", -1 } },
              { "travis_pololove", "", 500, { "", "", -1 } },
              { "travis_polofuck", "", 500, { "", "", -1 } },
              { "travis_polofucka3pl", "", 500, {"", "", -1 } },
              { "travis_polococacola", "", 500, { "", "", -1 } },
              { "travis_poloangelo", "", 500, { "", "", -1 } },
              { "travis_polomrbong", "", 500, { "", "", -1 } },
              { "travis_polomoon", "", 500, { "", "", -1 } },
              { "travis_polodino", "", 500, { "", "", -1 } },
              { "travis_polostunt", "", 500, { "", "", -1 } },
              { "travis_poloface", "", 500, { "", "", -1 } },
              { "travis_avengers", "", 500, { "", "", -1 } },
              { "travis_doge", "", 500, { "", "", -1 } },
              { "travis_fuckit", "", 500, { "", "", -1 } },
              { "travis_illuminati", "", 500, { "", "", -1 } },
              { "travis_jeff", "", 500, { "", "", -1 } },
              { "travis_kappa", "", 500, { "", "", -1 } },
              { "travis_married", "", 500, { "", "", -1 } },
              { "travis_marvel", "", 500, { "", "", -1 } },
              { "travis_mexicantroll", "", 500, { "", "", -1 } },
              { "travis_minion", "", 500, { "", "", -1 } },
              { "travis_monstercat", "", 500, { "", "", -1 } },
              { "travis_nike", "", 500, { "", "", -1 } },
              { "travis_pancake", "", 500, { "", "", -1 } },
              { "travis_shield", "", 500, { "", "", -1 } },
              { "travis_smile", "", 500, { "", "", -1 } },
              { "travis_Batman", "", 500, { "", "", -1 } },
              { "travis_tux", "", 500, { "", "", -1 } },
              { "travis_twitch", "", 500, { "", "", -1 } },
              { "travis_yaoming", "", 500, { "", "", -1 } },
              { "travis_smokeweed", "", 500, { "", "", -1 } },
              { "travis_Snoopy", "", 500, { "", "", -1 } },
              { "travis_Coco", "", 500, { "", "", -1 } },
              { "travis_Ciggy", "", 500, { "", "", -1 } },
              { "travis_Adidas", "", 500, { "", "", -1 } },
              {"KAEL_SUITS_BR_F","",135,""},
              {"KAEL_SUITS_BR_F3","",135,""},
              {"KAEL_SUITS_BR_F4","",135,""},
              {"KAEL_SUITS_BR_F5","",135,""},
              {"KAEL_SUITS_BR_F6","",135,""},
              {"KAEL_SUITS_BR_F7","",135,""},
              {"KAEL_SUITS_BR_F8","",135,""},
              {"KAEL_SUITS_BR_F9","",135,""},
              {"KAEL_SUITS_BR_F10","",135,""},
              {"KAEL_SUITS_BR_F11","",135,""},
              {"KAEL_SUITS_BR_F13","",135,""},
              {"KAEL_SUITS_BR_F14","",135,""},
              {"EF_suit_1","",135,""},
              {"EF_suit_2","",135,""},
              {"EF_suit_3","",135,""},
              {"EF_suit_4","",135,""},
              {"EF_suit_5","",135,""},
              {"EF_suit_6","",135,""},
              {"EF_FEM_3_42","",72,""},
              {"EF_FEM_3_3LPBPS","",72,""},
              {"EF_FEM_3_3LPBP","",72,""},
              {"EF_FEM_3_3LPBR","",72,""},
              {"EF_FEM_3_3LPBW","",72,""},
              {"EF_FEM_3_3LPB","",72,""},
              {"EF_FEM_3_3LPBL","",72,""},
              {"EF_FEM_3_3LPBPS2","",72,""},
              {"EF_FEM_3_3LPBP2","",72,""},
              {"EF_FEM_3_3LPBR2","",72,""},
              {"EF_FEM_3_3LPBW2","",72,""},
              {"EF_FEM_3_3LPB2","",72,""},
              {"EF_FEM_3_3LPBL2","",72,""},
              {"EF_FEM_3_75","",66,""},
              {"EF_FEM_3_75R","",66,""},
              {"EF_FEM_3_76","",66,""},
              {"EF_FEM_3_76R","",66,""},
              {"EF_FEM_3_73","",66,""},
              {"EF_FEM_3_73R","",66,""},
              {"EF_FEM_3_74","",66,""},
              {"EF_FEM_3_74R","",66,""},
              {"EF_FEM_3_7","",66,""},
              {"EF_FEM_3_7R","",66,""},
              {"EF_FEM_3_72","",66,""},
              {"EF_FEM_3_72R","",66,""},
              {"EF_FEM_3_5B","",66,""},
              {"EF_FEM_3_5BP","",66,""},
              {"EF_FEM_3_5VP","",66,""},
              {"EF_FEM_3_5RC","",66,""},
              {"EF_FEM_3_5W","",66,""},
              {"EF_FEM_3_52","",66,""},
              {"EF_FEM_3","",66,""},
              {"EF_FEM_4A","",66,""},
              {"EF_FEM_4A2","",66,""},
              {"EF_FEM_4A2_2","",66,""},
              {"EF_FEM_4_2LPBPS","",72,""},
              {"EF_FEM_4_2LPBP","",72,""},
              {"EF_FEM_4_2LPBR","",72,""},
              {"EF_FEM_4_2LPBL","",72,""},
              {"EF_FEM_4_2LPBPS2","",72,""},
              {"EF_FEM_4_2LPBR2","",72,""},
              {"EF_FEM_4_2LPBW2","",72,""},
              {"EF_FEM_4_2LPB2","",72,""},
              {"EF_FEM_4_2LPBL2","",72,""},
              {"EF_FEM_4_75","",66,""},
              {"EF_FEM_4_76","",66,""},
              {"EF_FEM_4_73","",66,""},
              {"EF_FEM_4_73R","",66,""},
              {"EF_FEM_4_74","",66,""},
              {"EF_FEM_4_7","",66,""},
              {"EF_FEM_4_72","",66,""},
              {"EF_FEM_4_4B","",66,""},
              {"EF_FEM_4_4BP","",66,""},
              {"EF_FEM_4_4VP","",66,""},
              {"EF_FEM_4_4RC","",66,""},
              {"EF_FEM_4_4W","",66,""},
              {"EF_FEM_5","",66,""},
              {"EF_FEM_62","",66,""},
              {"EF_FEM_6","",66,""},
              {"TRYK_U_B_PCUODHs","",250,""},
              {"TRYK_U_B_PCUGHs","",250,""},
              {"TRYK_U_B_PCUHs","",250,""},
              {"TRYK_U_B_BLOD_T","Black T Green P",50,""},
              {"TRYK_U_B_BLKTANR_CombatUniformTshirt","Black T Tan P II",70,""},
              {"TRYK_U_B_BLTAN_T","Black T Dark Tan P",50,""},
              {"TRYK_U_B_fleece_UCP","Leader",50,""},
              {"TRYK_U_B_ODTANR_CombatUniformTshirt","Green T Tan P",80,""},
              {"TRYK_U_B_PCUGs_OD","Jeans Green Hood",80,""},
              {"TRYK_U_B_PCUGs_gry","Jeans Gray Hood ",80,""},
              {"TRYK_U_B_PCUGs_BLK","Jeans Black Hood",80,""},
              {"TRYK_U_B_C02_Tsirt","Baggy Jeans + Black T",50,""},
              {"TRYK_OVERALL_SAGE_BLKboots_nk","Coveralls Green",40,""},
              {"TRYK_OVERALL_nok_flesh","Coveralls Tan",40,""},
              {"TRYK_U_B_wh_blk_Rollup_CombatUniform","White T Black Cargos",70,""},
              {"TRYK_U_B_wh_tan_Rollup_CombatUniform","White T Tan Cargos",70,""},
              {"TRYK_U_pad_hood_Blk","Black Hood Tan Cargos",10,""},
              {"TRYK_U_denim_hood_blk","Black Hood Jeans II",15,""},
              {"TRYK_U_denim_jersey_blk","Black T & Jeans",10,""},
              {"TRYK_U_denim_jersey_blu","Blue T & Jeans",10,""},
              {"TRYK_U_denim_hood_nc","Green Hood & Jeans",10,""},
              {"TRYK_U_taki_wh","Tan Mid East",10,""},
              {"TRYK_U_taki_BLK","Black Mid East",10,""},
              {"TRYK_U_taki_COY","Brown Mid East ",10,""},
              {"TRYK_U_B_BLK_T_BK","Black Jeans (Black)",50,""},
              {"TRYK_U_B_BLK_T_WH","Black Jeans (White)",50,""},
              {"TRYK_U_B_Denim_T_BK","Grey Jeans (Black)",50,""},
              {"TRYK_U_B_Denim_T_WH","Grey Jeans (White)",50,""},
          };

          headgear[] = {
              { "NONE", $STR_C_Remove_headgear, 0, "" },
              { "Gorb_KnittedHat2", "", 30, "" },
              { "Gorb_KnittedHat1", "", 30, "" },
              { "Gorb_KnittedHat3", "", 30, "" },
              { "Gorb_KnittedHat4", "", 30, "" },
              { "ALE_H_NewEra_Redsox", "", 30, "" },
              { "ALE_H_NewEra_Black", "", 30, "" },
              { "ALE_H_NewEra_Lakers", "", 30, "" },
              { "Gorb_KnittedHat2", "", 30, "" },
              { "Gorb_KnittedHat1", "", 30, "" },
              { "Gorb_KnittedHat3", "", 30, "" },
              { "Gorb_KnittedHat4", "", 30, "" },
              { "ALE_H_NewEra_Redsox", "", 30, "" },
              { "ALE_H_NewEra_Black", "", 30, "" },
              { "ALE_H_NewEra_Lakers", "", 30, "" },
              { "H_Bandanna_blu", "Blue Bandanna", 30, "" },
              { "H_Bandanna_surfer", "Surfer Bandanna", 35, "" },
              { "H_Bandanna_gry", "Grey Bandanna", 35, "" },
              { "H_Bandanna_cbr", "", 30, "" },
              { "H_Bandanna_surfer_grn", "", 15, "" },
              { "H_Bandanna_khk", "Khaki Bandanna", 30, "" },
              { "H_Bandanna_sgg", "Sage Bandanna", 20, "" },
              { "H_StrawHat", "Straw Fedora", 35, "" },
              { "H_BandMask_blk", "Hat & Bandanna", 30, "" },
              { "H_Booniehat_tan", "", 55, "" },
              { "H_Booniehat_oli", "", 55, "" },
              { "H_Booniehat_grn", "", 55, "" },
              { "H_Booniehat_dirty", "", 55, "" },
              { "H_Booniehat_khk_hs", "", 55, "" },
              { "H_H_MilCap_gry", "", 35, "" },
              { "H_MilCap_blue", "", 35, "" },
              { "H_Hat_blue", "", 40, "" },
              { "H_Hat_brown", "", 40, "" },
              { "H_Hat_checker", "", 70, "" },
              { "H_Hat_grey", "", 40, "" },
              { "H_Hat_tan", "", 30, "" },
              { "H_Cap_blu", "", 75, "" },
              { "H_Cap_blk", "", 75, "" },
              { "H_Cap_blk_CMMG", "", 75, "" },
              { "H_Cap_grn", "", 75, "" },
              { "H_Cap_grn_BI", "", 75, "" },
              { "H_Cap_blk_ION", "", 75, "" },
              { "H_Cap_usblack", "", 75, "" },
              { "H_Cap_surfer", "", 75, "" },
              { "H_Cap_oli", "", 75, "" },
              { "H_Cap_red", "", 75, "" },
              { "H_Cap_tan", "", 75, "" },
              { "H_ALFR_Metal_Facemask_gry", "", 30, "" },
              { "H_ALFR_Metal_Facemask_oli", "", 30, "" },
              { "H_ALFR_Metal_Facemask_sand", "", 30, "" },
              { "H_ALFR_Metal_Facemask_blk", "", 30, "" },
              { "H_MilCap_oucamo", "", 50, "" },
              { "H_MilCap_gen_F", "", 40, "" },
              { "H_MilCap_tna_F", "", 40, "" },
              { "H_Beret_gen_F", "", 200, "" },
              { "H_Bandanna_mcamo", "", 25, "" },
              { "H_Bandanna_camo", "", 25, "" },
              { "H_Booniehat_mcamo", "Booniehat (MTP)", 50, "" },
              { "H_Booniehat_indp", " Booniehat (Khaki)", 50, "" },
              { "H_Booniehat_tna_F", "Booniehat (Tropic)", 50, "" },
              { "H_TurbanO_blk", "Black Turban", 100, "" },
              { "H_Hat_camo", "", 100, "" },
              { "H_HelmetO_ocamo", "", 150, "" },
              { "H_HelmetO_ghex_F", "", 150, "" },
              { "H_HelmetB_light", "", 150, "" },
              { "H_HelmetB_light_desert", "", 150, "" },
              { "H_HelmetB_light_grass", "", 150, "" },
              { "H_HelmetB_light_sand", "", 150, "" },
              { "H_HelmetB_light_snakeskin", "", 200, "" },
              { "H_HelmetB_Light_tna_F", "", 200, "" },
              { "H_HelmetB_Enh_tna_F", "", 200, "" },
              { "H_HelmetB_paint", "", 200, "" },
              { "H_HelmetB_plain_mcamo", "", 200, "" },
              { "H_HelmetB_tna_F", "", 200, "" },
              { "H_HelmetIA_net", "", 200, "" },
              { "H_HelmetSpecO_ocamo", "", 200, "" },
              { "H_Shemag_tan", "", 125, "" },
              { "H_Shemag_olive_hs", "", 125, "" },
              { "H_ShemagOpen_tan", "", 125, "" },
              { "H_Shemag_olive", "", 125, "" },
              { "H_HelmetCrew_O_ghex_F", "", 300, "" },
              { "Gorb_RoughSantaClaus1", "Santa", 50, "" }
          };
          goggles[] = {
              { "NONE", $STR_C_Remove_goggles, 0, "" },
              { "G_Respirator_blue_F", "Mouth Mask", 50, "" },
              { "TRYK_kio_balaclava_WH", "White Mask", 50, "" },
              { "H_ALFR_SkiMask_1", "SkiMask 1", 50, "" },
              { "H_ALFR_SkiMask_2", "SkiMask 2", 50, "" },
              { "H_ALFR_SkiMask_3", "SkiMask 3", 50, "" },
              { "H_ALFR_SkiMask_4", "SkiMask 4", 50, "" },
              { "H_ALFR_SkiMask_5", "SkiMask 5", 50, "" },
              { "H_ALFR_SkiMask_6", "SkiMask 6", 50, "" },
              { "H_ALFR_SkiMask_7", "SkiMask 7", 50, "" },
              { "H_ALFR_SkiMask_8", "SkiMask 8", 50, "" },
              { "H_ALFR_SkiMask_9", "SkiMask 9", 50, "" }
          };
          vests[] = {
              { "NONE", $STR_C_Remove_vests, 0, "" },
              { "V_Safety_blue_F", "Saftey Blue", 50, "" },
              { "V_Safety_orange_F", "Saftey Orange", 50, "" },
              { "V_Chestrig_khk", "", 300, "" },
              { "V_TacVest_brn", "", 1550, "" },
              { "V_TacVest_camo", "", 1550, "" },
              { "V_TacVest_khk", "", 1550, "" },
              { "V_TacVest_oli", "", 1550, "" },
              { "V_PlateCarrierIA1_dgtl", "", 3650, "" },
              { "V_PlateCarrier2_rgr", "", 4450, "" },
              { "VSM_FAPC_Operator_AOR1", "", 4650, "" },
              { "VSM_LBT6094_MG_AOR1", "", 6450, "" },
              { "VSM_RAV_operator_M81", "", 6450, "" },
              { "VSM_RAV_MG_AOR1", "", 6850, "" },
              { "VSM_RAV_Breacher_M81", "", 6850, "" },
              { "V_Safety_yellow_F", "Saftey Yellow", 50, "" }
          };
          backpacks[] = {
              { "NONE", $STR_C_Remove_backpacks, 0, "" },
              { "CL3_ParachutePackAmerica", "American Parachute", 50, "" },
              { "cl3_civ_tacticalbelt", "Backpack Belt", 50, "" },
              { "koilgucci", "Gucci Bag", 1500, "" },
              { "kaelmonty", "", 50, "" },
              { "kaelmonty2", "", 50, "" },
              { "kaelmario", "", 50, "" },
              { "kaelsuits", "", 50, "" },
              { "koilbatman_1", "", 50, "" },
              { "koilbender_1", "", 50, "" },
              { "koilbender_2", "", 50, "" },
              { "koilclint_1", "", 50, "" },
              { "koileminem_1", "", 50, "" },
              { "koilgraf_1", "", 50, "" },
              { "koilgraf_2", "", 50, "" },
              { "koilgraf_3", "", 50, "" },
              { "koilhulk_1", "", 50, "" },
              { "koiljoker_1", "", 50, "" },
              { "koilpumpkin_1", "", 50, "" },
              { "koilsparta_1", "", 50, "" },
              { "koilsponge_1", "", 50, "" },
              { "koilturtles_1", "", 50, "" },
              { "B_OutdoorPack_blk", "", 150, "" },
              { "B_AssaultPack_khk", "", 200, "" },
              { "B_AssaultPack_dgtl", "", 200, "" },
              { "B_AssaultPack_rgr", "", 200, "" },
              { "B_AssaultPack_sgg", "", 200, "" },
              { "B_AssaultPack_blk", "", 200, "" },
              { "B_AssaultPack_cbr", "", 200, "" },
              { "B_AssaultPack_mcamo", "", 200, "" },
              { "B_AssaultPack_tna_f", "", 200, "" },
              { "B_TacticalPack_oli", "", 200, "" },
              { "B_Kitbag_mcamo", "", 300, "" },
              { "B_Kitbag_sgg", "", 300, "" },
              { "B_Kitbag_cbr", "", 300, "" },
              { "B_FieldPack_blk", "", 400, "" },
              { "B_FieldPack_ocamo", "", 400, "" },
              { "B_FieldPack_oucamo", "", 400, "" },
              { "B_FieldPack_ghex_f", "", 400, "" },
              { "B_Bergen_sgg", "", 500, "" },
              { "B_Bergen_mcamo", "", 500, "" },
              { "B_Bergen_rgr", "", 500, "" },
              { "B_Bergen_blk", "", 500, "" },
              { "B_Carryall_ocamo", "", 550, "" },
              { "B_Carryall_oucamo", "", 550, "" },
              { "B_Carryall_mcamo", "", 550, "" },
              { "B_Carryall_oli", "", 550, "" },
              { "B_Carryall_khk", "", 550, "" },
              { "B_Carryall_cbr", "", 550, "" },
              { "B_Carryall_ghex_f", "", 650, "" },
              { "B_Bergen_dgtl_f", "", 650, "" },
              { "koilkatie", "", 50, "" },
              { "koilpanda", "", 50, "" },
              { "koilaiden", "", 50, "" },
              { "koileagle", "", 50, "" },
              { "koilspecktators", "", 50, "" },
              { "koildarth", "", 50, "" },
              { "koilsmashing", "", 50, "" },
              { "koilgoonsquad", "", 50, "" },
              { "koilcat", "", 50, "" },
              { "koilbp_1", "", 50, "" },
              { "koilbp_2", "", 50, "" },
              { "koilbp_3", "", 50, "" },
              { "koilbp_4", "", 50, "" },
              { "koilbp_5", "", 50, "" },
              { "koilbp_6", "", 50, "" },
              { "koilbp_7", "", 50, "" },
              { "koilbp_8", "", 50, "" },
              { "koilbp_9", "", 50, "" },
              { "koilbp_10", "", 50, "" },
              { "koilbp_11", "", 50, "" },
              { "koilbp_12", "", 50, "" },
              { "koilbp_13", "", 50, "" },
              { "koilbp_14", "", 50, "" },
              { "koilbp_15", "", 50, "" },
              { "koilbp_16", "", 50, "" },
              { "koilbp_17", "", 50, "" },
              { "koilbp_18", "", 50, "" },
              { "koilbp_19", "", 50, "" },
              { "koilbp_20", "", 50, "" },
              { "koilbp_21", "", 50, "" },
              { "B_AssaultPack_mcamo", "", 200, "" },
              { "B_TacticalPack_oli", "", 250, "" },
              { "B_Kitbag_mcamo", "", 300, "" },
              { "B_Kitbag_sgg", "", 300, "" },
              { "B_Kitbag_cbr", "", 300, "" },
              { "B_FieldPack_blk", "", 500, "" },
              { "B_FieldPack_ocamo", "", 500, "" },
              { "B_FieldPack_oucamo", "", 500, "" },
              { "B_Bergen_sgg", "", 650, "" },
              { "B_Bergen_mcamo", "", 650, "" },
              { "B_Bergen_rgr", "", 650, "" },
              { "B_Bergen_blk", "", 650, "" },
              { "B_Carryall_ocamo", "", 750, "" },
              { "B_Carryall_oucamo", "", 750, "" },
              { "B_Carryall_mcamo", "", 750, "" },
              { "B_Carryall_oli", "", 750, "" },
              { "B_Carryall_khk", "", 750, "" },
              { "B_Carryall_cbr", "", 750, "" },
              { "B_Bergen_dgtl_f", "", 1650, "" },
              { "cg_invisbp", "", 1650, "" },
              { "koilbp_22", "", 50, "" }
          };
      };
    class bruce {
        title = "STR_Shops_C_Bruce";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_C_Scientist", "Radiation Suit", 500, "" },
            { "travis_polocookiemonster", "", 500, { "", "", -1 } },
            { "travis_polosecurity", "", 500, { "", "", -1 } },
            { "travis_poloapple", "", 500, { "", "", -1 } },
            { "travis_polohellokitty", "", 500, { "", "", -1 } },
            { "travis_polohellokitty1", "", 500, { "", "", -1 } },
            { "travis_timmac", "", 500, { "", "", -1 } },
            { "travis_Butts", "", 500, { "", "", -1 } },
            { "travis_poloaustralia", "", 500, { "", "", -1 } },
            { "travis_polospongebob", "", 500, { "", "", -1 } },
            { "travis_polopatrickstar", "", 500, { "", "", -1 } },
            { "travis_polocanda", "", 500, { "", "", -1 } },
            { "travis_pololove", "", 500, { "", "", -1 } },
            { "travis_polofuck", "", 500, { "", "", -1 } },
            { "travis_polofucka3pl", "", 500, {"", "", -1 } },
            { "travis_polococacola", "", 500, { "", "", -1 } },
            { "travis_poloangelo", "", 500, { "", "", -1 } },
            { "travis_polomrbong", "", 500, { "", "", -1 } },
            { "travis_polomoon", "", 500, { "", "", -1 } },
            { "travis_polodino", "", 500, { "", "", -1 } },
            { "travis_polostunt", "", 500, { "", "", -1 } },
            { "travis_poloface", "", 500, { "", "", -1 } },
            { "travis_avengers", "", 500, { "", "", -1 } },
            { "travis_doge", "", 500, { "", "", -1 } },
            { "travis_fuckit", "", 500, { "", "", -1 } },
            { "travis_illuminati", "", 500, { "", "", -1 } },
            { "travis_jeff", "", 500, { "", "", -1 } },
            { "travis_kappa", "", 500, { "", "", -1 } },
            { "travis_married", "", 500, { "", "", -1 } },
            { "travis_marvel", "", 500, { "", "", -1 } },
            { "travis_mexicantroll", "", 500, { "", "", -1 } },
            { "travis_minion", "", 500, { "", "", -1 } },
            { "travis_monstercat", "", 500, { "", "", -1 } },
            { "travis_nike", "", 500, { "", "", -1 } },
            { "travis_pancake", "", 500, { "", "", -1 } },
            { "travis_shield", "", 500, { "", "", -1 } },
            { "travis_smile", "", 500, { "", "", -1 } },
            { "travis_Batman", "", 500, { "", "", -1 } },
            { "travis_tux", "", 500, { "", "", -1 } },
            { "travis_twitch", "", 500, { "", "", -1 } },
            { "travis_yaoming", "", 500, { "", "", -1 } },
            { "travis_smokeweed", "", 500, { "", "", -1 } },
            { "travis_Snoopy", "", 500, { "", "", -1 } },
            { "travis_Coco", "", 500, { "", "", -1 } },
            { "travis_Ciggy", "", 500, { "", "", -1 } },
            { "travis_Adidas", "", 500, { "", "", -1 } },
            {"KAEL_SUITS_BR_F","",135,""},
            {"KAEL_SUITS_BR_F3","",135,""},
            {"KAEL_SUITS_BR_F4","",135,""},
            {"KAEL_SUITS_BR_F5","",135,""},
            {"KAEL_SUITS_BR_F6","",135,""},
            {"KAEL_SUITS_BR_F7","",135,""},
            {"KAEL_SUITS_BR_F8","",135,""},
            {"KAEL_SUITS_BR_F9","",135,""},
            {"KAEL_SUITS_BR_F10","",135,""},
            {"KAEL_SUITS_BR_F11","",135,""},
            {"KAEL_SUITS_BR_F13","",135,""},
            {"KAEL_SUITS_BR_F14","",135,""}
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "H_CrewHelmetHeli_B", "Hazmat Breather", 350, "" },
            { "Gorb_KnittedHat2", "", 30, "" },
            { "Gorb_KnittedHat1", "", 30, "" },
            { "Gorb_KnittedHat3", "", 30, "" },
            { "Gorb_KnittedHat4", "", 30, "" },
            { "Gorb_MrsClaus1", "", 30, "" },
            { "Gorb_MrsClaus3", "", 30, "" },
            { "ALE_H_NewEra_Redsox", "", 30, "" },
            { "ALE_H_NewEra_Black", "", 30, "" },
            { "ALE_H_NewEra_Lakers", "", 30, "" },
            { "Kio_No1_Hat", "", 30, "" },
            { "Gorb_Penguin", "", 30, "" },
            { "Kio_Pirate_Hat", "", 30, "" },
            { "Gorb_Reindeer", "", 30, "" },
            { "Gorb_RoughSantaClaus1", "", 30, "" },
            { "H_ALFR_Samurai_Mask", "", 30, "" },
            { "Gorb_SantaHat", "", 30, "" },
            { "Gorb_TreeMask1", "", 30, "" },
            { "turban", "", 30, "" },
            { "Gorb_TurkeyMask1", "", 30, "" },
            { "Gorb_UglyMrsClaus1", "", 30, "" },
            { "Kio_Hat", "", 30, "" },
            { "H_Capbw_pmc", "", 30, "" },
            { "Kio_Afro_Hat", "", 30, "" },
            { "Gorb_AngryGingerbread3", "", 30, "" },
            { "kio_vfv_mask", "", 30, "" },
            { "Kio_Capital_Hat", "", 30, "" },
            { "Gorb_PuddingHat", "", 30, "" },
            { "ALE_H_Cowboy_Black", "", 30, "" },
            { "EF_FBNE_BL", "", 30, "" },
            { "Gorb_FestiveHat1", "", 30, "" },
            { "kio_skl_msk_GOW", "", 30, "" },
            { "H_ALFR_Metal_Facemask_gry", "", 30, "" },
            { "H_ALFR_Metal_Facemask_oli", "", 30, "" },
            { "H_ALFR_Metal_Facemask_sand", "", 30, "" },
            { "H_ALFR_Metal_Facemask_blk", "", 30, "" },
            { "cg_horsehead", "", 30, "" },
            { "cg_horsehead_2", "", 30, "" },
            { "H_ALFR_Metal_Facemask_blk", "", 30, "" },
            { "H_Bandanna_blu", "Blue Bandanna", 30, "" },
            { "H_Bandanna_surfer", "Surfer Bandanna", 35, "" },
            { "H_Bandanna_gry", "Grey Bandanna", 35, "" },
            { "H_Bandanna_cbr", "", 30, "" },
            { "H_Bandanna_surfer_grn", "", 15, "" },
            { "H_Bandanna_khk", "Khaki Bandanna", 30, "" },
            { "H_Bandanna_sgg", "Sage Bandanna", 20, "" },
            { "H_StrawHat", "Straw Fedora", 35, "" },
            { "H_BandMask_blk", "Hat & Bandanna", 30, "" },
            { "H_Booniehat_tan", "", 55, "" },
            { "H_Booniehat_oli", "", 55, "" },
            { "H_Booniehat_grn", "", 55, "" },
            { "H_Booniehat_dirty", "", 55, "" },
            { "H_Booniehat_khk_hs", "", 55, "" },
            { "H_H_MilCap_gry", "", 35, "" },
            { "H_MilCap_blue", "", 35, "" },
            { "H_Hat_blue", "", 40, "" },
            { "H_Hat_brown", "", 40, "" },
            { "H_Hat_checker", "", 70, "" },
            { "H_Hat_grey", "", 40, "" },
            { "H_Hat_tan", "", 30, "" },
            { "H_Cap_blu", "", 75, "" },
            { "H_Cap_blk", "", 75, "" },
            { "H_Cap_blk_CMMG", "", 75, "" },
            { "H_Cap_grn", "", 75, "" },
            { "H_Cap_grn_BI", "", 75, "" },
            { "H_Cap_blk_ION", "", 75, "" },
            { "H_Cap_usblack", "", 75, "" },
            { "H_Cap_surfer", "", 75, "" },
            { "H_Cap_oli", "", 75, "" },
            { "H_Cap_red", "", 75, "" },
            { "H_Cap_tan", "", 75, "" },
            { "H_Helmet_Skate", "", 30, "" },
            { "H_Watchcap_sgg", "", 45, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Shades_Black", "", 20, "" },
            { "G_Shades_Blue", "", 20, "" },
            { "G_Shades_Green", "", 20, "" },
            { "G_Shades_Red", "", 20, "" },
            { "G_Sport_Blackred", "", 25, "" },
            { "G_Sport_BlackWhite", "", 25, "" },
            { "G_Sport_Blackyellow", "", 25, "" },
            { "G_Sport_Checkered", "", 25, "" },
            { "G_Sport_Greenblack", "", 25, "" },
            { "G_Sport_Red", "", 25, "" },
            { "G_Lowprofile", "", 30, "" },
            { "G_Squares", "", 35, "" },
            { "G_Aviator", "", 25, "" },
            { "G_Combat", "", 25, "" },
            { "G_Lady_Mirror", "", 15, "" },
            { "G_Lady_Dark", "", 15, "" },
            { "G_Lady_Blue", "", 15, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_Press_F", "", 450, "" },
            {"d3s_vest_1", 250, "true", ""},
            {"d3s_vest_1_a", 250, "true", ""},
            {"d3s_vest_1_b", 250, "true", ""},
            {"d3s_vest_1_c", 250, "true", ""},
            {"d3s_vest_1_d", 250, "true", ""},
            {"d3s_vest_1_e", 250, "true", ""},
            {"d3s_vest_1_f", 250, "true", ""},
            {"d3s_vest_1_g", 250, "true", ""},
            {"d3s_vest_1_h", 250, "true", ""},
            {"d3s_vest_1_i", 250, "true", ""},
            {"d3s_vest_1_j", 250, "true", ""},
            {"d3s_vest_1_k", 250, "true", ""},
            {"d3s_vest_1_l", 250, "true", ""},
            {"d3s_vest_1_m", 250, "true", ""},
            {"d3s_vest_1_n", 250, "true", ""},
            {"d3s_vest_1_o", 250, "true", ""},
            {"d3s_vest_1_p", 250, "true", ""},
            {"d3s_vest_1_q", 250, "true", ""},
            {"d3s_vest_1_r", 250, "true", ""},
            {"d3s_vest_1_s", 250, "true", ""},
            {"d3s_vest_1_t", 250, "true", ""},
            {"d3s_vest_1_u", 250, "true", ""},
            {"d3s_vest_1_v", 250, "true", ""},
            {"d3s_vest_1_w", 250, "true", ""},
            {"d3s_vest_1_x", 250, "true", ""},
            {"d3s_vest_1_y", 250, "true", ""},
            {"d3s_vest_1_z", 250, "true", ""}
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "casper_beautifulbackpack", "", 700, { "", "", -1 } },
            { "casper_cockbackpack", "", 700, { "", "", -1 } },
            { "casper_facbackpack", "", 700, { "", "", -1 } },
            { "casper_hellokittybackpack", "", 700, { "", "", -1 } },
            { "casper_mcdonaldsbackpack", "", 700, { "", "", -1 } },
            { "casper_nemobackpack", "", 700, { "", "", -1 } },
            { "casper_ppatrolbackpack", "", 700, { "", "", -1 } },
            { "B_Bergen_sgg", "", 500, "" },
            { "B_Bergen_mcamo", "", 500, "" },
            { "B_Bergen_rgr", "", 500, "" },
            { "B_Bergen_blk", "", 500, "" },
            { "B_Carryall_ocamo", "", 550, "" },
            { "B_Carryall_oucamo", "", 550, "" },
            { "B_Carryall_mcamo", "", 550, "" },
            { "B_Carryall_oli", "", 550, "" },
            { "B_Carryall_khk", "", 550, "" },
            { "B_Carryall_cbr", "", 550, "" }
        };
    };

    class VIP {
        title = "STR_Shops_VIP";
        conditions = "call life_donorlevel >= 1";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "cg_beats1", "", 250, "" },
            { "cg_bipolar1", "", 250, "" },
            { "cg_burgerking1", "", 250, "" },
            { "cg_catvideos1", "", 250, "" },
            { "cg_condoms1", "", 250, "" },
            { "cg_csgo1", "", 250, "" },
            { "cg_deeznuts1", "", 250, "" },
            { "cg_hearts1", "", 250, "" },
            { "cg_illuminati1", "", 250, "" },
            { "U_C_ConstructionCoverall_Black_F", "", 250, "" },
            { "TRYK_U_B_PCUHsW3", "", 250, "" },
            { "TRYK_U_B_Snow_CombatUniform", "", 250, "" },
            { "TRYK_ZARATAKI", "", 250, "" },
            { "U_O_Protagonist_VR", "", 250, "" },
            { "vacationshirt_uni", "", 250, "" },
            { "TRYK_U_B_PCUHsW", "", 250, "" },
            { "HITMAN_47_SUIT", "", 250, "" },
            {"KAEL_SUITS_BR_F","",135,""},
            {"KAEL_SUITS_BR_F3","",135,""},
            {"KAEL_SUITS_BR_F4","",135,""},
            {"KAEL_SUITS_BR_F5","",135,""},
            {"KAEL_SUITS_BR_F6","",135,""},
            {"KAEL_SUITS_BR_F7","",135,""},
            {"KAEL_SUITS_BR_F8","",135,""},
            {"KAEL_SUITS_BR_F9","",135,""},
            {"KAEL_SUITS_BR_F10","",135,""},
            {"KAEL_SUITS_BR_F11","",135,""},
            {"KAEL_SUITS_BR_F13","",135,""},
            {"KAEL_SUITS_BR_F14","",135,""},
            {"EF_suit_1","",135,""},
            {"EF_suit_2","",135,""},
            {"EF_suit_3","",135,""},
            {"EF_suit_4","",135,""},
            {"EF_suit_5","",135,""},
            {"EF_suit_6","",135,""},
            {"EF_FEM_3_42","",72,""},
            {"EF_FEM_3_3LPBPS","",72,""},
            {"EF_FEM_3_3LPBP","",72,""},
            {"EF_FEM_3_3LPBR","",72,""},
            {"EF_FEM_3_3LPBW","",72,""},
            {"EF_FEM_3_3LPB","",72,""},
            {"EF_FEM_3_3LPBL","",72,""},
            {"EF_FEM_3_3LPBPS2","",72,""},
            {"EF_FEM_3_3LPBP2","",72,""},
            {"EF_FEM_3_3LPBR2","",72,""},
            {"EF_FEM_3_3LPBW2","",72,""},
            {"EF_FEM_3_3LPB2","",72,""},
            {"EF_FEM_3_3LPBL2","",72,""},
            {"EF_FEM_3_75","",66,""},
            {"EF_FEM_3_75R","",66,""},
            {"EF_FEM_3_76","",66,""},
            {"EF_FEM_3_76R","",66,""},
            {"EF_FEM_3_73","",66,""},
            {"EF_FEM_3_73R","",66,""},
            {"EF_FEM_3_74","",66,""},
            {"EF_FEM_3_74R","",66,""},
            {"EF_FEM_3_7","",66,""},
            {"EF_FEM_3_7R","",66,""},
            {"EF_FEM_3_72","",66,""},
            {"EF_FEM_3_72R","",66,""},
            {"EF_FEM_3_5B","",66,""},
            {"EF_FEM_3_5BP","",66,""},
            {"EF_FEM_3_5VP","",66,""},
            {"EF_FEM_3_5RC","",66,""},
            {"EF_FEM_3_5W","",66,""},
            {"EF_FEM_3_52","",66,""},
            {"EF_FEM_3","",66,""},
            {"EF_FEM_4A","",66,""},
            {"EF_FEM_4A2","",66,""},
            {"EF_FEM_4A2_2","",66,""},
            {"EF_FEM_4_2LPBPS","",72,""},
            {"EF_FEM_4_2LPBP","",72,""},
            {"EF_FEM_4_2LPBR","",72,""},
            {"EF_FEM_4_2LPBL","",72,""},
            {"EF_FEM_4_2LPBPS2","",72,""},
            {"EF_FEM_4_2LPBR2","",72,""},
            {"EF_FEM_4_2LPBW2","",72,""},
            {"EF_FEM_4_2LPB2","",72,""},
            {"EF_FEM_4_2LPBL2","",72,""},
            {"EF_FEM_4_75","",66,""},
            {"EF_FEM_4_76","",66,""},
            {"EF_FEM_4_73","",66,""},
            {"EF_FEM_4_73R","",66,""},
            {"EF_FEM_4_74","",66,""},
            {"EF_FEM_4_7","",66,""},
            {"EF_FEM_4_72","",66,""},
            {"EF_FEM_4_4B","",66,""},
            {"EF_FEM_4_4BP","",66,""},
            {"EF_FEM_4_4VP","",66,""},
            {"EF_FEM_4_4RC","",66,""},
            {"EF_FEM_4_4W","",66,""},
            {"EF_FEM_5","",66,""},
            {"EF_FEM_62","",66,""},
            {"EF_FEM_6","",66,""},
            {"TRYK_U_B_PCUODHs","",250,""},
            {"TRYK_U_B_PCUGHs","",250,""},
            {"TRYK_U_B_PCUHs","",250,""},
            {"TRYK_U_B_BLOD_T","Black T Green P",50,""},
            {"TRYK_U_B_BLKTANR_CombatUniformTshirt","Black T Tan P II",70,""},
            {"TRYK_U_B_BLTAN_T","Black T Dark Tan P",50,""},
            {"TRYK_U_B_fleece_UCP","Leader",50,""},
            {"TRYK_U_B_ODTANR_CombatUniformTshirt","Green T Tan P",80,""},
            {"TRYK_U_B_PCUGs_OD","Jeans Green Hood",80,""},
            {"TRYK_U_B_PCUGs_gry","Jeans Gray Hood ",80,""},
            {"TRYK_U_B_PCUGs_BLK","Jeans Black Hood",80,""},
            {"TRYK_U_B_C02_Tsirt","Baggy Jeans + Black T",50,""},
            {"TRYK_OVERALL_SAGE_BLKboots_nk","Coveralls Green",40,""},
            {"TRYK_OVERALL_nok_flesh","Coveralls Tan",40,""},
            {"TRYK_U_B_wh_blk_Rollup_CombatUniform","White T Black Cargos",70,""},
            {"TRYK_U_B_wh_tan_Rollup_CombatUniform","White T Tan Cargos",70,""},
            {"TRYK_U_pad_hood_Blk","Black Hood Tan Cargos",10,""},
            {"TRYK_U_denim_hood_blk","Black Hood Jeans II",15,""},
            {"TRYK_U_denim_jersey_blk","Black T & Jeans",10,""},
            {"TRYK_U_denim_jersey_blu","Blue T & Jeans",10,""},
            {"TRYK_U_denim_hood_nc","Green Hood & Jeans",10,""},
            {"TRYK_U_taki_wh","Tan Mid East",10,""},
            {"TRYK_U_taki_BLK","Black Mid East",10,""},
            {"TRYK_U_taki_COY","Brown Mid East ",10,""},
            {"TRYK_U_B_BLK_T_BK","Black Jeans (Black)",50,""},
            {"TRYK_U_B_BLK_T_WH","Black Jeans (White)",50,""},
            {"TRYK_U_B_Denim_T_BK","Grey Jeans (Black)",50,""},
            {"TRYK_U_B_Denim_T_WH","Grey Jeans (White)",50,""},
            {"d3s_uniform_jbib_008_a", 250, "true", ""},
            {"d3s_uniform_jbib_008_aa", 250, "true", ""},
            {"d3s_uniform_jbib_008_ab", 250, "true", ""},
            {"d3s_uniform_jbib_008_ac", 250, "true", ""},
            {"d3s_uniform_jbib_008_ad", 250, "true", ""},
            {"d3s_uniform_jbib_008_ae", 250, "true", ""},
            {"d3s_uniform_jbib_008_af", 250, "true", ""},
            {"d3s_uniform_jbib_008_b", 250, "true", ""},
            {"d3s_uniform_jbib_008_ba", 250, "true", ""},
            {"d3s_uniform_jbib_008_bb", 250, "true", ""},
            {"d3s_uniform_jbib_008_bc", 250, "true", ""},
            {"d3s_uniform_jbib_008_bd", 250, "true", ""},
            {"d3s_uniform_jbib_008_be", 250, "true", ""},
            {"d3s_uniform_jbib_008_bf", 250, "true", ""},
            {"d3s_uniform_jbib_008_c", 250, "true", ""},
            {"d3s_uniform_jbib_008_ca", 250, "true", ""},
            {"d3s_uniform_jbib_008_cb", 250, "true", ""},
            {"d3s_uniform_jbib_008_cc", 250, "true", ""},
            {"d3s_uniform_jbib_008_cd", 250, "true", ""},
            {"d3s_uniform_jbib_008_ce", 250, "true", ""},
            {"d3s_uniform_jbib_008_cf", 250, "true", ""},
            {"d3s_uniform_jbib_008_d", 250, "true", ""},
            {"d3s_uniform_jbib_008_da", 250, "true", ""},
            {"d3s_uniform_jbib_008_db", 250, "true", ""},
            {"d3s_uniform_jbib_008_dc", 250, "true", ""},
            {"d3s_uniform_jbib_008_dd", 250, "true", ""},
            {"d3s_uniform_jbib_008_de", 250, "true", ""},
            {"d3s_uniform_jbib_008_df", 250, "true", ""},
            {"d3s_uniform_jbib_008_e", 250, "true", ""},
            {"d3s_uniform_jbib_008_ea", 250, "true", ""},
            {"d3s_uniform_jbib_008_eb", 250, "true", ""},
            {"d3s_uniform_jbib_008_ec", 250, "true", ""},
            {"d3s_uniform_jbib_008_ed", 250, "true", ""},
            {"d3s_uniform_jbib_008_ee", 250, "true", ""},
            {"d3s_uniform_jbib_008_ef", 250, "true", ""},
            {"d3s_uniform_jbib_008_f", 250, "true", ""},
            {"d3s_uniform_jbib_008_fa", 250, "true", ""},
            {"d3s_uniform_jbib_008_fb", 250, "true", ""},
            {"d3s_uniform_jbib_008_fc", 250, "true", ""},
            {"d3s_uniform_jbib_008_fd", 250, "true", ""},
            {"d3s_uniform_jbib_008_fe", 250, "true", ""},
            {"d3s_uniform_jbib_008_ff", 250, "true", ""},
            {"d3s_uniform_jbib_008_g", 250, "true", ""},
            {"d3s_uniform_jbib_008_ga", 250, "true", ""},
            {"d3s_uniform_jbib_008_gb", 250, "true", ""},
            {"d3s_uniform_jbib_008_gc", 250, "true", ""},
            {"d3s_uniform_jbib_008_gd", 250, "true", ""},
            {"d3s_uniform_jbib_008_ge", 250, "true", ""},
            {"d3s_uniform_jbib_008_gf", 250, "true", ""},
            {"d3s_uniform_jbib_008_h", 250, "true", ""},
            {"d3s_uniform_jbib_008_ha", 250, "true", ""},
            {"d3s_uniform_jbib_008_hb", 250, "true", ""},
            {"d3s_uniform_jbib_008_hc", 250, "true", ""},
            {"d3s_uniform_jbib_008_hd", 250, "true", ""},
            {"d3s_uniform_jbib_008_he", 250, "true", ""},
            {"d3s_uniform_jbib_008_hf", 250, "true", ""},
            {"d3s_uniform_jbib_008_i", 250, "true", ""},
            {"d3s_uniform_jbib_008_ia", 250, "true", ""},
            {"d3s_uniform_jbib_008_ib", 250, "true", ""},
            {"d3s_uniform_jbib_008_ic", 250, "true", ""},
            {"d3s_uniform_jbib_008_id", 250, "true", ""},
            {"d3s_uniform_jbib_008_ie", 250, "true", ""},
            {"d3s_uniform_jbib_008_if", 250, "true", ""},
            {"d3s_uniform_jbib_008_j", 250, "true", ""},
            {"d3s_uniform_jbib_008_ja", 250, "true", ""},
            {"d3s_uniform_jbib_008_jb", 250, "true", ""},
            {"d3s_uniform_jbib_008_jc", 250, "true", ""},
            {"d3s_uniform_jbib_008_jd", 250, "true", ""},
            {"d3s_uniform_jbib_008_je", 250, "true", ""},
            {"d3s_uniform_jbib_008_jf", 250, "true", ""},
            {"d3s_uniform_jbib_008_k", 250, "true", ""},
            {"d3s_uniform_jbib_008_ka", 250, "true", ""},
            {"d3s_uniform_jbib_008_kb", 250, "true", ""},
            {"d3s_uniform_jbib_008_kc", 250, "true", ""},
            {"d3s_uniform_jbib_008_kd", 250, "true", ""},
            {"d3s_uniform_jbib_008_ke", 250, "true", ""},
            {"d3s_uniform_jbib_008_kf", 250, "true", ""},
            {"d3s_uniform_jbib_008_l", 250, "true", ""},
            {"d3s_uniform_jbib_008_la", 250, "true", ""},
            {"d3s_uniform_jbib_008_lb", 250, "true", ""},
            {"d3s_uniform_jbib_008_lc", 250, "true", ""},
            {"d3s_uniform_jbib_008_ld", 250, "true", ""},
            {"d3s_uniform_jbib_008_le", 250, "true", ""},
            {"d3s_uniform_jbib_008_lf", 250, "true", ""},
            {"d3s_uniform_jbib_008_m", 250, "true", ""},
            {"d3s_uniform_jbib_008_ma", 250, "true", ""},
            {"d3s_uniform_jbib_008_mb", 250, "true", ""},
            {"d3s_uniform_jbib_008_mc", 250, "true", ""},
            {"d3s_uniform_jbib_008_md", 250, "true", ""},
            {"d3s_uniform_jbib_008_me", 250, "true", ""},
            {"d3s_uniform_jbib_008_mf", 250, "true", ""},
            {"d3s_uniform_jbib_008_n", 250, "true", ""},
            {"d3s_uniform_jbib_008_na", 250, "true", ""},
            {"d3s_uniform_jbib_008_nb", 250, "true", ""},
            {"d3s_uniform_jbib_008_nc", 250, "true", ""},
            {"d3s_uniform_jbib_008_nd", 250, "true", ""},
            {"d3s_uniform_jbib_008_ne", 250, "true", ""},
            {"d3s_uniform_jbib_008_nf", 250, "true", ""},
            {"d3s_uniform_jbib_008_o", 250, "true", ""},
            {"d3s_uniform_jbib_008_oa", 250, "true", ""},
            {"d3s_uniform_jbib_008_ob", 250, "true", ""},
            {"d3s_uniform_jbib_008_oc", 250, "true", ""},
            {"d3s_uniform_jbib_008_od", 250, "true", ""},
            {"d3s_uniform_jbib_008_oe", 250, "true", ""},
            {"d3s_uniform_jbib_008_of", 250, "true", ""}
        };

        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "SAN_SantaHat", "", 30, "" },
            { "Gorb_KnittedHat2", "", 30, "" },
            { "Gorb_KnittedHat1", "", 30, "" },
            { "Gorb_KnittedHat3", "", 30, "" },
            { "Gorb_KnittedHat4", "", 30, "" },
            { "Gorb_MrsClaus1", "", 30, "" },
            { "Gorb_MrsClaus3", "", 30, "" },
            { "ALE_H_NewEra_Redsox", "", 30, "" },
            { "ALE_H_NewEra_Black", "", 30, "" },
            { "ALE_H_NewEra_Lakers", "", 30, "" },
            { "Kio_No1_Hat", "", 30, "" },
            { "Gorb_Penguin", "", 30, "" },
            { "Kio_Pirate_Hat", "", 30, "" },
            { "Gorb_Reindeer", "", 30, "" },
            { "Gorb_RoughSantaClaus1", "", 30, "" },
            { "H_ALFR_Samurai_Mask", "", 30, "" },
            { "Gorb_SantaHat", "", 30, "" },
            { "Gorb_TreeMask1", "", 30, "" },
            { "turban", "", 30, "" },
            { "Gorb_TurkeyMask1", "", 30, "" },
            { "Gorb_UglyMrsClaus1", "", 30, "" },
            { "Kio_Hat", "", 30, "" },
            { "H_Capbw_pmc", "", 30, "" },
            { "Kio_Afro_Hat", "", 30, "" },
            { "Gorb_AngryGingerbread3", "", 30, "" },
            { "kio_vfv_mask", "", 30, "" },
            { "Kio_Capital_Hat", "", 30, "" },
            { "Gorb_PuddingHat", "", 30, "" },
            { "ALE_H_Cowboy_Black", "", 30, "" },
            { "EF_FBNE_BL", "", 30, "" },
            { "Gorb_FestiveHat1", "", 30, "" },
            { "kio_skl_msk_GOW", "", 30, "" },
            { "H_ALFR_Metal_Facemask_gry", "", 30, "" },
            { "H_ALFR_Metal_Facemask_oli", "", 30, "" },
            { "H_ALFR_Metal_Facemask_sand", "", 30, "" },
            { "H_ALFR_Metal_Facemask_blk", "", 30, "" },
            { "H_ShemagOpen_khk", "", 140, "" },
            { "H_Beret_gen_F", "", 200, "" },
            { "H_Bandanna_mcamo", "", 250, "" },
            { "H_Bandanna_camo", "", 250, "" },
            { "H_Booniehat_mcamo", "Booniehat (MTP)", 50, "" },
            { "H_Booniehat_indp", " Booniehat (Khaki)", 50, "" },
            { "H_Booniehat_tna_F", "Booniehat (Tropic)", 50, "" },
            { "H_TurbanO_blk", "Black Turban", 50, "" },
            { "H_GingerbreadMask", "Gingerbread Mask", 50, "" },
            { "Gorb_Gingerbread1", "Gingerbread Mask2", 50, "" },
            { "H_GuyFawkesMask", "Anonymous Mask", 50, "" },
            { "H_Construction_basic_orange_F", "Hardhat", 50, "" },
            { "cg_horsehead_pnk", "Horse Hat", 50, "" },
            { "H_KermitMask", "Kermit Hat", 50, "" },
            { "H_MickeyMask", "Mickey Mask", 50, "" },
            { "Gorb_MrsClaus1", "Mrs Claus", 50, "" },
            { "H_ObamaMask", "Obama Mask", 50, "" },
            { "Gorb_Penguin", "Penguin", 50, "" },
            { "Gorb_RoughSantaClaus1", "Santa", 50, "" },
            {"d3s_CAP_christmas_head_a", 250, "true", ""},
            {"d3s_CAP_christmas_head_b", 250, "true", ""},
            {"d3s_CAP_christmas_head_c", 250, "true", ""},
            {"d3s_CAP_christmas_head_d", 250, "true", ""},
            {"d3s_CAP_christmas_head_e", 250, "true", ""},
            {"d3s_CAP_christmas_head_f", 250, "true", ""},
            {"d3s_CAP_christmas_head_g", 250, "true", ""},
            {"d3s_CAP_christmas_head_h", 250, "true", ""},
            {"d3s_CAP_christmas_head1", 250, "true", ""},
            {"d3s_CAP_christmas_head2_a", 250, "true", ""},
            {"d3s_CAP_christmas_head2_b", 250, "true", ""},
            {"d3s_CAP_christmas_head2_c", 250, "true", ""},
            {"d3s_CAP_christmas_head2_d", 250, "true", ""},
            {"d3s_CAP_christmas_head3_a", 250, "true", ""},
            {"d3s_CAP_christmas_head3_b", 250, "true", ""},
            {"d3s_CAP_christmas_head3_c", 250, "true", ""},
            {"d3s_CAP_christmas_head3_d", 250, "true", ""},
            {"d3s_CAP_christmas_head4_a", 250, "true", ""},
            {"d3s_CAP_christmas_head4_b", 250, "true", ""},
            {"d3s_CAP_christmas_head4_c", 250, "true", ""},
            {"d3s_CAP_christmas_head4_d", 250, "true", ""},
            {"d3s_CAP_christmas_head4_e", 250, "true", ""},
            {"d3s_CAP_christmas_head4_f", 250, "true", ""},
            {"d3s_CAP_christmas_head4_g", 250, "true", ""},
            {"d3s_CAP_christmas_head4_h", 250, "true", ""},
            {"d3s_CAP_christmas_head5_a", 250, "true", ""},
            {"d3s_CAP_christmas_head5_b", 250, "true", ""},
            {"d3s_CAP_christmas_head5_c", 250, "true", ""},
            {"d3s_CAP_christmas_head5_d", 250, "true", ""},
            {"d3s_CAP_christmas_head5_e", 250, "true", ""},
            {"d3s_CAP_christmas_head5_f", 250, "true", ""},
            {"d3s_CAP_christmas_head5_g", 250, "true", ""},
            {"d3s_CAP_christmas_head5_h", 250, "true", ""},
            {"d3s_CAP_p_head_000_a", 250, "true", ""},
            {"d3s_CAP_p_head_000_b", 250, "true", ""},
            {"d3s_CAP_p_head_000_c", 250, "true", ""},
            {"d3s_CAP_p_head_000_d", 250, "true", ""},
            {"d3s_CAP_p_head_000_e", 250, "true", ""},
            {"d3s_CAP_p_head_000_f", 250, "true", ""},
            {"d3s_CAP_p_head_000_g", 250, "true", ""},
            {"d3s_CAP_p_head_000_h", 250, "true", ""},
            {"d3s_CAP_p_head_000_i", 250, "true", ""},
            {"d3s_CAP_p_head_000_j", 250, "true", ""},
            {"d3s_CAP_p_head_000_k", 250, "true", ""},
            {"d3s_CAP_p_head_000_l", 250, "true", ""},
            {"d3s_CAP_p_head_000_m", 250, "true", ""},
            {"d3s_CAP_p_head_000_n", 250, "true", ""},
            {"d3s_CAP_p_head_000_o", 250, "true", ""},
            {"d3s_CAP_p_head_000_p", 250, "true", ""},
            {"d3s_CAP_p_head_000_q", 250, "true", ""},
            {"d3s_CAP_p_head_000_r", 250, "true", ""},
            {"d3s_CAP_p_head_000_s", 250, "true", ""},
            {"d3s_CAP_p_head_000_t", 250, "true", ""},
            {"d3s_CAP_p_head_001_a", 250, "true", ""},
            {"d3s_CAP_p_head_001_b", 250, "true", ""},
            {"d3s_CAP_p_head_001_c", 250, "true", ""},
            {"d3s_CAP_p_head_001_d", 250, "true", ""},
            {"d3s_CAP_p_head_001_e", 250, "true", ""},
            {"d3s_CAP_p_head_001_f", 250, "true", ""},
            {"d3s_CAP_p_head_001_g", 250, "true", ""},
            {"d3s_CAP_p_head_001_h", 250, "true", ""},
            {"d3s_CAP_p_head_001_i", 250, "true", ""},
            {"d3s_CAP_p_head_001_j", 250, "true", ""},
            {"d3s_CAP_p_head_004_a", 250, "true", ""},
            {"d3s_CAP_p_head_004_b", 250, "true", ""},
            {"d3s_CAP_p_head_004_c", 250, "true", ""},
            {"d3s_CAP_p_head_004_d", 250, "true", ""},
            {"d3s_CAP_p_head_004_e", 250, "true", ""},
            {"d3s_CAP_p_head_004_f", 250, "true", ""},
            {"d3s_CAP_p_head_004_g", 250, "true", ""},
            {"d3s_CAP_p_head_004_h", 250, "true", ""},
            {"d3s_CAP_p_head_004_i", 250, "true", ""},
            {"d3s_CAP_p_head_004_j", 250, "true", ""},
            {"d3s_CAP_p_head_004_k", 250, "true", ""},
            {"d3s_CAP_p_head_004_l", 250, "true", ""},
            {"d3s_CAP_p_head_004_m", 250, "true", ""},
            {"d3s_CAP_p_head_005_a", 250, "true", ""},
            {"d3s_CAP_p_head_005_b", 250, "true", ""},
            {"d3s_CAP_p_head_005_c", 250, "true", ""},
            {"d3s_CAP_p_head_005_d", 250, "true", ""},
            {"d3s_CAP_p_head_005_e", 250, "true", ""},
            {"d3s_CAP_p_head_005_f", 250, "true", ""},
            {"d3s_CAP_p_head_005_g", 250, "true", ""},
            {"d3s_CAP_p_head_005_h", 250, "true", ""},
            {"d3s_CAP_p_head_005_i", 250, "true", ""},
            {"d3s_CAP_p_head_005_j", 250, "true", ""},
            {"d3s_CAP_p_head_005_k", 250, "true", ""},
            {"d3s_CAP_p_head_005_l", 250, "true", ""},
            {"d3s_CAP_p_head_005_m", 250, "true", ""},
            {"d3s_CAP_p_head_005_n", 250, "true", ""},
            {"d3s_CAP_p_head_005_o", 250, "true", ""},
            {"d3s_CAP_p_head_005_p", 250, "true", ""},
            {"d3s_CAP_p_head_005_q", 250, "true", ""},
            {"d3s_CAP_p_head_005_r", 250, "true", ""},
            {"d3s_CAP_p_head_005_s", 250, "true", ""},
            {"d3s_CAP_p_head_005_t", 250, "true", ""},
            {"d3s_CAP_p_head_005_u", 250, "true", ""},
            {"d3s_CAP_p_head_005_v", 250, "true", ""},
            {"d3s_CAP_p_head_005_w", 250, "true", ""},
            {"d3s_CAP_p_head_005_x", 250, "true", ""},
            {"d3s_CAP_p_head_005_y", 250, "true", ""},
            {"d3s_CAP_p_head_005_z", 250, "true", ""},
            {"d3s_CAP_p_head_006_a", 250, "true", ""},
            {"d3s_CAP_p_head_006_b", 250, "true", ""},
            {"d3s_CAP_berd_000_u_a", 250, "true", ""},
            {"d3s_CAP_berd_000_u_b", 250, "true", ""},
            {"d3s_CAP_berd_000_u_c", 250, "true", ""},
            {"d3s_CAP_berd_000_u_d", 250, "true", ""},
            {"d3s_CAP_berd_000_u_e", 250, "true", ""},
            {"d3s_CAP_berd_002_u_a", 250, "true", ""},
            {"d3s_CAP_berd_002_u_b", 250, "true", ""},
            {"d3s_CAP_berd_002_u_c", 250, "true", ""},
            {"d3s_CAP_berd_002_u_d", 250, "true", ""},
            {"d3s_CAP_berd_002_u_e", 250, "true", ""},
            {"d3s_CAP_berd_002_u_f", 250, "true", ""},
            {"d3s_CAP_berd_002_u_g", 250, "true", ""},
            {"d3s_CAP_berd_002_u_h", 250, "true", ""},
            {"d3s_CAP_berd_002_u_i", 250, "true", ""},
            {"d3s_CAP_berd_002_u_j", 250, "true", ""},
            {"d3s_CAP_berd_002_u_k", 250, "true", ""},
            {"d3s_CAP_berd_002_u_l", 250, "true", ""},
            {"d3s_CAP_berd_002_u_m", 250, "true", ""},
            {"d3s_CAP_berd_002_u_n", 250, "true", ""},
            {"d3s_CAP_berd_002_u_o", 250, "true", ""},
            {"d3s_CAP_berd_002_u_p", 250, "true", ""},
            {"d3s_CAP_berd_002_u_q", 250, "true", ""},
            {"d3s_CAP_berd_002_u_r", 250, "true", ""},
            {"d3s_CAP_berd_002_u_s", 250, "true", ""},
            {"d3s_CAP_berd_002_u_t", 250, "true", ""},
            {"d3s_CAP_berd_002_u_u", 250, "true", ""},
            {"d3s_CAP_berd_002_u_v", 250, "true", ""},
            {"d3s_CAP_berd_002_u_w", 250, "true", ""},
            {"d3s_CAP_berd_002_u_x", 250, "true", ""},
            {"d3s_CAP_berd_002_u_y", 250, "true", ""},
            {"d3s_CAP_berd_002_u_z", 250, "true", ""},
            {"d3s_CAP_berd_003_u_a", 250, "true", ""},
            {"d3s_CAP_berd_003_u_b", 250, "true", ""},
            {"d3s_CAP_berd_003_u_c", 250, "true", ""},
            {"d3s_CAP_berd_003_u_d", 250, "true", ""},
            {"d3s_CAP_berd_003_u_e", 250, "true", ""},
            {"d3s_CAP_berd_003_u_f", 250, "true", ""},
            {"d3s_CAP_berd_003_u_g", 250, "true", ""},
            {"d3s_CAP_berd_003_u_h", 250, "true", ""},
            {"d3s_CAP_berd_003_u_i", 250, "true", ""},
            {"d3s_CAP_berd_003_u_j", 250, "true", ""},
            {"d3s_CAP_berd_003_u_k", 250, "true", ""},
            {"d3s_CAP_berd_003_u_l", 250, "true", ""},
            {"d3s_CAP_berd_003_u_m", 250, "true", ""},
            {"d3s_CAP_berd_003_u_n", 250, "true", ""},
            {"d3s_CAP_berd_003_u_o", 250, "true", ""},
            {"d3s_CAP_berd_003_u_p", 250, "true", ""},
            {"d3s_CAP_berd_003_u_q", 250, "true", ""},
            {"d3s_CAP_berd_003_u_r", 250, "true", ""},
            {"d3s_CAP_berd_003_u_s", 250, "true", ""},
            {"d3s_CAP_berd_003_u_t", 250, "true", ""},
            {"d3s_CAP_berd_003_u_u", 250, "true", ""},
            {"d3s_CAP_berd_003_u_v", 250, "true", ""},
            {"d3s_CAP_berd_003_u_w", 250, "true", ""},
            {"d3s_CAP_berd_003_u_x", 250, "true", ""},
            {"d3s_CAP_berd_003_u_y", 250, "true", ""},
            {"d3s_CAP_berd_003_u_z", 250, "true", ""},
            {"d3s_CAP_berd_004_u_a", 250, "true", ""},
            {"d3s_CAP_berd_004_u_b", 250, "true", ""},
            {"d3s_CAP_berd_004_u_c", 250, "true", ""},
            {"d3s_CAP_berd_004_u_d", 250, "true", ""},
            {"d3s_CAP_berd_004_u_e", 250, "true", ""},
            {"d3s_CAP_berd_004_u_f", 250, "true", ""},
            {"d3s_CAP_berd_004_u_g", 250, "true", ""},
            {"d3s_CAP_berd_004_u_i", 250, "true", ""},
            {"d3s_CAP_berd_004_u_k", 250, "true", ""},
            {"d3s_CAP_berd_004_u_n", 250, "true", ""},
            {"d3s_CAP_berd_004_u_s", 250, "true", ""},
            {"d3s_CAP_berd_004_u_j", 250, "true", ""},
            {"d3s_CAP_berd_006_u_a", 250, "true", ""},
            {"d3s_CAP_berd_006_u_b", 250, "true", ""},
            {"d3s_CAP_berd_006_u_c", 250, "true", ""},
            {"d3s_CAP_berd_006_u_d", 250, "true", ""},
            {"d3s_CAP_berd_006_u_e", 250, "true", ""},
            {"d3s_CAP_berd_006_u_f", 250, "true", ""},
            {"d3s_CAP_berd_006_u_g", 250, "true", ""},
            {"d3s_CAP_berd_006_u_h", 250, "true", ""},
            {"d3s_CAP_berd_006_u_i", 250, "true", ""},
            {"d3s_CAP_berd_006_u_j", 250, "true", ""},
            {"d3s_CAP_berd_006_u_k", 250, "true", ""},
            {"d3s_CAP_berd_006_u_l", 250, "true", ""},
            {"d3s_CAP_berd_006_u_m", 250, "true", ""},
            {"d3s_CAP_berd_006_u_n", 250, "true", ""},
            {"d3s_CAP_berd_011_u_a", 250, "true", ""},
            {"d3s_CAP_berd_011_u_b", 250, "true", ""},
            {"d3s_CAP_berd_011_u_c", 250, "true", ""},
            {"d3s_CAP_berd_011_u_d", 250, "true", ""},
            {"d3s_CAP_berd_011_u_e", 250, "true", ""},
            {"d3s_CAP_berd_011_u_f", 250, "true", ""},
            {"d3s_CAP_berd_011_u_g", 250, "true", ""},
            {"d3s_CAP_berd_011_u_h", 250, "true", ""},
            {"d3s_CAP_berd_011_u_i", 250, "true", ""},
            {"d3s_CAP_berd_011_u_j", 250, "true", ""},
            {"d3s_CAP_berd_011_u_k", 250, "true", ""},
            {"d3s_CAP_berd_011_u_l", 250, "true", ""},
            {"d3s_CAP_berd_011_u_m", 250, "true", ""},
            {"d3s_CAP_berd_011_u_n", 250, "true", ""},
            {"d3s_CAP_berd_011_u_o", 250, "true", ""},
            {"d3s_CAP_berd_011_u_p", 250, "true", ""},
            {"d3s_CAP_berd_011_u_q", 250, "true", ""},
            {"d3s_CAP_berd_011_u_r", 250, "true", ""},
            {"d3s_CAP_berd_011_u_s", 250, "true", ""},
            {"d3s_CAP_berd_011_u_t", 250, "true", ""},
            {"d3s_CAP_berd_011_u_u", 250, "true", ""},
            {"d3s_CAP_berd_011_u_v", 250, "true", ""},
            {"d3s_CAP_berd_011_u_w", 250, "true", ""},
            {"d3s_CAP_berd_011_u_x", 250, "true", ""},
            {"d3s_CAP_char_sniper", 250, "true", ""},
            {"d3s_CAP_beanie", 250, "true", ""},
            {"d3s_CAP_beanie1", 250, "true", ""},
            {"d3s_CAP_beanie2", 250, "true", ""},
            {"d3s_CAP_beanie3", 250, "true", ""},
            {"d3s_CAP_beanie4", 250, "true", ""},
            {"d3s_CAP_beanie5", 250, "true", ""},
            {"d3s_CAP_beanie6", 250, "true", ""},
            {"d3s_CAP_beanie7", 250, "true", ""},
            {"d3s_CAP_beanie8", 250, "true", ""},
            {"d3s_CAP_beanie_1", 250, "true", ""},
            {"d3s_CAP_beanie_1_a", 250, "true", ""},
            {"d3s_CAP_beanie_1_b", 250, "true", ""},
            {"d3s_CAP_beanie_1_c", 250, "true", ""},
            {"d3s_CAP_beanie_1_d", 250, "true", ""},
            {"d3s_CAP_beanie_1_e", 250, "true", ""},
            {"d3s_CAP_beanie_1_f", 250, "true", ""},
            {"d3s_CAP_beanie_1_g", 250, "true", ""},
            {"d3s_CAP_beanie_1_h", 250, "true", ""},
            {"d3s_CAP_beanie_1_i", 250, "true", ""},
            {"d3s_CAP_beanie_1_j", 250, "true", ""},
            {"d3s_CAP_beanie_1_k", 250, "true", ""},
            {"d3s_CAP_beanie_1_l", 250, "true", ""},
            {"d3s_CAP_beanie_1_m", 250, "true", ""},
            {"d3s_CAP_beanie_2_a", 250, "true", ""},
            {"d3s_CAP_beanie_2_b", 250, "true", ""},
            {"d3s_CAP_beanie_2_c", 250, "true", ""},
            {"d3s_CAP_beanie_2_d", 250, "true", ""},
            {"d3s_CAP_beanie_2_e", 250, "true", ""},
            {"d3s_CAP_beanie_2_f", 250, "true", ""},
            {"d3s_CAP_beanie_2_g", 250, "true", ""},
            {"d3s_CAP_beanie_2_h", 250, "true", ""},
            {"d3s_CAP_beanie_2_i", 250, "true", ""},
            {"d3s_CAP_beanie_2_j", 250, "true", ""},
            {"d3s_CAP_beanie_2_k", 250, "true", ""},
            {"d3s_CAP_beanie_2_l", 250, "true", ""},
            {"d3s_CAP_beanie_2_m", 250, "true", ""},
            {"d3s_CAP_beanie_2_n", 250, "true", ""},
            {"d3s_CAP_beanie_2_o", 250, "true", ""},
            {"d3s_CAP_Embacy", 250, "true", ""},
            {"d3s_CAP_furcap", 250, "true", ""},
            {"d3s_CAP_russelite_hat", 250, "true", ""},
            {"d3s_CAP_Headgear", 250, "true", ""},
            {"d3s_CAP_Headgear1", 250, "true", ""},
            {"d3s_CAP_Headgear_1", 250, "true", ""},
            {"d3s_CAP_Headgear1_1", 250, "true", ""}
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Respirator_blue_F", "Mouth Mask", 50, "" },
            { "TRYK_kio_balaclava_WH", "White Mask", 50, "" },
            { "H_ALFR_SkiMask_1", "SkiMask 1", 50, "" },
            { "H_ALFR_SkiMask_2", "SkiMask 2", 50, "" },
            { "H_ALFR_SkiMask_3", "SkiMask 3", 50, "" },
            { "H_ALFR_SkiMask_4", "SkiMask 4", 50, "" },
            { "H_ALFR_SkiMask_5", "SkiMask 5", 50, "" },
            { "H_ALFR_SkiMask_6", "SkiMask 6", 50, "" },
            { "H_ALFR_SkiMask_7", "SkiMask 7", 50, "" },
            { "H_ALFR_SkiMask_8", "SkiMask 8", 50, "" },
            { "H_ALFR_SkiMask_9", "SkiMask 9", 50, "" },
            { "d3s_p_eyes_000_a", "", 50, "" },
            { "d3s_p_eyes_000_b", "", 50, "" },
            { "d3s_p_eyes_000_c", "", 50, "" },
            { "d3s_p_eyes_000_d", "", 50, "" },
            { "d3s_p_eyes_000_e", "", 50, "" },
            { "d3s_p_eyes_000_f", "", 50, "" },
            { "d3s_p_eyes_000_g", "", 50, "" },
            { "d3s_p_eyes_000_h", "", 50, "" },
            { "d3s_p_eyes_000_i", "", 50, "" },
            { "d3s_p_eyes_000_j", "", 50, "" },
            { "d3s_p_eyes_000_k", "", 50, "" },
            { "d3s_p_eyes_000_l", "", 50, "" },
            { "d3s_p_eyes_000_m", "", 50, "" },
            { "d3s_p_eyes_000_n", "", 50, "" },
            { "d3s_p_eyes_000_o", "", 50, "" },
            { "d3s_p_eyes_001", "", 50, "" },
            { "d3s_Glasses_scarf_a", "", 50, "" },
            { "d3s_Glasses_scarf_b", "", 50, "" },
            { "d3s_Glasses_scarf_c", "", 50, "" },
            { "d3s_Glasses_scarf_d", "", 50, "" },
            { "d3s_Glasses_scarf1_a", "", 50, "" },
            { "d3s_Glasses_scarf1_b", "", 50, "" },
            { "d3s_Glasses_scarf1_c", "", 50, "" },
            { "d3s_Glasses_scarf1_d", "", 50, "" },
            { "d3s_Glasses_scarf2_a", "", 50, "" },
            { "d3s_Glasses_scarf2_b", "", 50, "" },
            { "d3s_Glasses_scarf2_c", "", 50, "" },
            { "d3s_Glasses_scarf2_d", "", 50, "" },
            { "d3s_Glasses_scarf2_e", "", 50, "" },
            { "d3s_Glasses_scarf2_f", "", 50, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_Safety_blue_F", "Saftey Blue", 50, "" },
            { "V_Safety_orange_F", "Saftey Orange", 50, "" },
            { "V_Safety_yellow_F", "Saftey Yellow", 50, "" },
            { "accs_diff_000", "", 450, "" },
            { "d3s_vest_1", "", 450, "" },
            { "d3s_vest_1_a", "", 450, "" },
            { "d3s_vest_1_b", "", 450, "" },
            { "d3s_vest_1_c", "", 450, "" },
            { "d3s_vest_1_d", "", 450, "" },
            { "d3s_vest_1_e", "", 450, "" },
            { "d3s_vest_1_f", "", 450, "" },
            { "d3s_vest_1_g", "", 450, "" },
            { "d3s_vest_1_h", "", 450, "" },
            { "d3s_vest_1_i", "", 450, "" },
            { "d3s_vest_1_j", "", 450, "" },
            { "d3s_vest_1_k", "", 450, "" },
            { "d3s_vest_1_l", "", 450, "" },
            { "d3s_vest_1_m", "", 450, "" },
            { "d3s_vest_1_n", "", 450, "" },
            { "d3s_vest_1_o", "", 450, "" },
            { "d3s_vest_1_p", "", 450, "" },
            { "d3s_vest_1_q", "", 450, "" },
            { "d3s_vest_1_r", "", 450, "" },
            { "d3s_vest_1_s", "", 450, "" },
            { "d3s_vest_1_t", "", 450, "" },
            { "d3s_vest_1_u", "", 450, "" },
            { "d3s_vest_1_v", "", 450, "" },
            { "d3s_vest_1_w", "", 450, "" },
            { "d3s_vest_1_x", "", 450, "" },
            { "d3s_vest_1_y", "", 450, "" },
            { "d3s_vest_1_z", "", 450, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "CL3_ParachutePackAmerica", "American Parachute", 50, "" },
            { "cl3_civ_tacticalbelt", "Backpack Belt", 50, "" },
            { "koilgucci", "Gucci Bag", 1500, "" },
            { "kaelmonty", "", 50, "" },
            { "kaelmonty2", "", 50, "" },
            { "kaelmario", "", 50, "" },
            { "kaelsuits", "", 50, "" },
            { "koilbatman_1", "", 50, "" },
            { "koilbender_1", "", 50, "" },
            { "koilbender_2", "", 50, "" },
            { "koilclint_1", "", 50, "" },
            { "koileminem_1", "", 50, "" },
            { "koilgraf_1", "", 50, "" },
            { "koilgraf_2", "", 50, "" },
            { "koilgraf_3", "", 50, "" },
            { "koilhulk_1", "", 50, "" },
            { "koiljoker_1", "", 50, "" },
            { "koilpumpkin_1", "", 50, "" },
            { "koilsparta_1", "", 50, "" },
            { "koilsponge_1", "", 50, "" },
            { "koilturtles_1", "", 50, "" },
            { "koilkatie", "", 50, "" },
            { "koilpanda", "", 50, "" },
            { "koilaiden", "", 50, "" },
            { "koileagle", "", 50, "" },
            { "koilspecktators", "", 50, "" },
            { "koildarth", "", 50, "" },
            { "koilsmashing", "", 50, "" },
            { "koilgoonsquad", "", 50, "" },
            { "koilcat", "", 50, "" },
            { "koilbp_1", "", 50, "" },
            { "koilbp_2", "", 50, "" },
            { "koilbp_3", "", 50, "" },
            { "koilbp_4", "", 50, "" },
            { "koilbp_5", "", 50, "" },
            { "koilbp_6", "", 50, "" },
            { "koilbp_7", "", 50, "" },
            { "koilbp_8", "", 50, "" },
            { "koilbp_9", "", 50, "" },
            { "koilbp_10", "", 50, "" },
            { "koilbp_11", "", 50, "" },
            { "koilbp_12", "", 50, "" },
            { "koilbp_13", "", 50, "" },
            { "koilbp_14", "", 50, "" },
            { "koilbp_15", "", 50, "" },
            { "koilbp_16", "", 50, "" },
            { "koilbp_17", "", 50, "" },
            { "koilbp_18", "", 50, "" },
            { "koilbp_19", "", 50, "" },
            { "koilbp_20", "", 50, "" },
            { "koilbp_21", "", 50, "" },
            { "koilbp_22", "", 50, "" },
            { "cg_invisbp", "", 800, "" },
            { "d3s_backpack", "", 800, "" },
            { "d3s_backpack_a", "", 800, "" },
            { "d3s_backpack_b", "", 800, "" },
            { "d3s_backpack_c", "", 800, "" },
            { "d3s_backpack_d", "", 800, "" },
            { "d3s_backpack_e", "", 800, "" },
            { "d3s_backpack_f", "", 800, "" },
            { "d3s_backpack_g", "", 800, "" },
            { "d3s_backpack_h", "", 800, "" },
            { "d3s_backpack_i", "", 800, "" },
            { "d3s_backpack_j", "", 800, "" },
            { "d3s_backpack_k", "", 800, "" },
            { "d3s_backpack_l", "", 800, "" },
            { "d3s_backpack_m", "", 800, "" }
        };
    };

    class cop {
        title = "STR_Shops_C_Police";
        conditions = "";
        side = "cop";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },

            { "AR_PoliceU_ST_Ofc", "", 20, "" },
            { "AR_PoliceU_ST_Snr", "", 20, "" },
            { "AR_PoliceU_ST_Cpl", "", 20, "" },
            { "AR_PoliceU_ST_Sgt", "", 20, "" },
            { "AR_PoliceU_ST_CSgt", "", 20, "" },
            { "AR_PoliceU_ST_Lt", "", 20, "" },
            { "AR_PoliceU_ST_Cpt", "", 20, "" },

            { "A3LJumperCIDBlack", "SWAT Command", 20, "" },
            { "SWAT_GREY_UNIFORM", "SWAT Operation", 20, "" },
            { "CPE_SWAT_Uniform_4", "SWAT Casual", 20, "" },
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "AM_PatrolHat", "Patrol Hat", 25, "" },
            { "H_Cap_police", "Police Cap Blue", 25, "" },
            { "H_Beret_blk", "LT Beret", 25, "" },
            { "DRP_DOC_BERET", "DOC Cpt Beret", 25, "" },
            { "DRP_POLICE_BERET", "Patrol Cpt Beret", 25, "" },
            { "DRP_SWAT_BERET", "S.W.A.T Command Beret", 25, "" },
            { "AM_PatrolHat", "Patrol Hat", 25, "" },
            { "CPE_SWAT_FAST_2", "", 25, "" },
            { "H_Beret_02", "State Command Beret", 25, "" },
            { "H_Beret_Colonel", "Chief's Beret", 25, "" },
            { "HRP_POLICE_HAT", "Police Cap", 25, "" }
			
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "CPE_MK50", "SWAT Gasmask", 150, "" },
            { "d3s_CAP_berd_003_u_glasses", "SWAT Balaclava", 150, "" },
            { "Mask_M50", "Gasmask", 150, "" },
            { "TRYK_kio_balaclava_BLK", "", 150, "" },
            { "H_ALFR_SkiMask_Glasses_1", "", 25, "" },
            { "pmc_earpiece", "", 30, "" },
            { "G_Aviator", "", 10, "" },
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "AR_SWAT_BLK_VEST", "", 200, "" },
            { "AR_Sec_SWAT_Vest", "", 200, "" },
            { "AR_SC_Chief_Vest", "", 200, "" },
            { "AR_SC_Com_Vest", "", 200, "" },
            { "AR_SC_AssChief_Vest", "", 200, "" },
            { "AR_SC_DepC_Vest", "", 200, "" },
            { "AR_SC_Sup_Vest", "", 200, "" },
            { "AR_SC_Insp_Vest", "", 200, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "cl3_police_tacticalbelt", "Police Belt", 70, "" },
            { "B_Bag_Searchlight", "", 465, "" },
            { "CPE_SWAT_AssaultPack_4", "SWAT Backpack", 350, "" }
        };
    };

    class dive {
        title = "STR_Shops_C_Diving";
        conditions = "license_civ_dive";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_B_Wetsuit", "", 2000, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Diving", "", 500, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_RebreatherB", "", 5000, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" }
        };
    };

    class doj {
        title = "Department Of Justice Clothing";
        conditions = "license_civ_doj";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
              {"KAEL_SUITS_BR_F","",135,""},
              {"KAEL_SUITS_BR_F3","",135,""},
              {"KAEL_SUITS_BR_F4","",135,""},
              {"KAEL_SUITS_BR_F5","",135,""},
              {"KAEL_SUITS_BR_F6","",135,""},
              {"KAEL_SUITS_BR_F7","",135,""},
              {"KAEL_SUITS_BR_F8","",135,""},
              {"KAEL_SUITS_BR_F9","",135,""},
              {"KAEL_SUITS_BR_F10","",135,""},
              {"KAEL_SUITS_BR_F11","",135,""},
              {"KAEL_SUITS_BR_F13","",135,""},
              {"KAEL_SUITS_BR_F14","",135,""},
              {"EF_suit_1","",135,""},
              {"EF_suit_2","",135,""},
              {"EF_suit_3","",135,""},
              {"EF_suit_4","",135,""},
              {"EF_suit_5","",135,""},
              {"EF_suit_6","",135,""}
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" }
        };
    };

    class cop_boat {
        title = "STR_Shops_C_Diving";
        conditions = "";
        side = "cop";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_B_Wetsuit", "", 200, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Diving", "", 10, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_RebreatherB", "", 100, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "B_ViperHarness_blk_F", "", 200, "" }
        };
    };

    class gun_clothing {
        title = "STR_Shops_C_Gun";
        conditions = "license_civ_gun";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" }
        };
    };

    class gang_clothing {
        title = "STR_Shops_C_Gang";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" }
        };
    };

    class med_clothing {
        title = "STR_MAR_EMS_Clothing_Shop";
        conditions = "";
        side = "med";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "ADT_EMS_Uniform12", "EMS G1 Uniform", 50, "" },
            { "ADT_EMS_Uniform3", "EMS G2/3 Uniform", 50, "" },
            { "ADT_EMS_Uniform5", "EMS G4/5 Uniform", 50, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "H_Cap_grn", "EMS G1 Cap", 10, "" },
            { "H_Cap_blu", "EMS G2/3 Cap", 10, "" },
            { "H_Cap_red", "EMS G4/5 Cap", 10, "" },
            { "ADT_EMS_FlightHelmet", "S&R Pilot Helmet", 10, "" },
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_I_Diving", "", 10, "S&R Diving Goggles" },
            { "G_WirelessEarpiece_F", "", 10, "Command Earpiece" },
            { "Mask_M50", "", 10, "HazMat Mask" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "cl3_police_vest_pm", "EMT Vest", 10, "" },
            { "cl3_police_vest_fd", "Fire Casual Vest", 10, "" },
            { "cl3_police_vest_fd", "S&R Pilot Vest", 10, "" },
            { "V_RebreatherIA", "S&R Diving Vest", 10, "" },
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "cl3_emt_tacticalbelt_black", "EMT Tactical Belt", 10, "" },
            { "tf_rt1523g_black", "Dispatch Radio", 10, "" }
        };
    };

    class reb {
        title = "STR_Shops_C_Rebel";
        conditions = "(missionNamespace getVariable ['mav_ttm_var_rebel',0]) isEqualTo 1";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_I_C_Soldier_Bandit_5_F", "", 150, "" },
            { "U_I_C_Soldier_Bandit_3_F", "", 150, "" },
            { "KAEL_SUITS_BR_F24", "", 1000, "" },
            { "KAEL_SUITS_BR_F25", "", 1000, "" },
            { "KAEL_SUITS_BR_F16", "", 1000, "" },
            { "KAEL_SUITS_BR_F26", "", 1000, "" },
            { "KAEL_SUITS_BR_F27", "", 1000, "" },
            { "KAEL_SUITS_BR_F30", "", 1000, "" },
            { "KAEL_SUITS_BR_F32", "", 1000, "" },
            { "KAEL_SUITS_BR_F34", "", 1000, "" },
            { "KAEL_SUITS_BR_F35", "", 1000, "" },
            { "EF_HM_LPBW", "", 150, "" },
            { "EF_HM_LPB", "", 150, "" },
            { "EF_HM_LPBL", "", 150, "" },
            { "EF_HM_LPBPS2", "", 150, "" },
            { "EF_HM_LPB2", "", 150, "" },
            { "EF_HM_LPBR", "", 150, "" },
            { "HITMAN_47_SUIT", "", 1500, "" },
            { "KAEL_SUITS_BLK_F", "", 1000, "" },
            { "KAEL_SUITS_BR_F11", "", 1000, "" },
            { "KAEL_SUITS_BR_F10", "", 1000, "" },
            { "KAEL_SUITS_BR_F9", "", 1000, "" },
            { "KAEL_SUITS_BR_F", "", 1000, "" },
            { "KAEL_SUITS_BR_F13", "", 1000, "" },
            { "KAEL_SUITS_BR_F14", "", 1000, "" },
            { "KAEL_SUITS_BR_F5", "", 1000, "" },

            { "TRYK_U_B_BLK", "", 1000, "" },
            { "U_PMC_CombatUniformLS_ChckLB_GPBB", "", 350, "" },
            { "U_PMC_CombatUniformLS_BSSPBB", "", 350, "" },
            { "U_PMC_CombatUniformLS_GSSPBB", "", 350, "" },
            { "U_PMC_CombatUniformLS_SSBPBB", "", 350, "" },
            { "U_PMC_CombatUniformLS_ChckLR_SPBB", "", 350, "" },
            { "TRYK_U_B_ARO1_CBR_R_CombatUniform", "", 350, "" },
            { "TRYK_U_B_ARO1_GR_CombatUniform", "", 350, "" },
            { "TRYK_U_B_ARO1_GRY_CombatUniform", "", 350, "" },
            { "TRYK_DMARPAT_T", "", 350, "" },
            { "TRYK_U_B_AOR2_BLK_R_CombatUniform", "", 350, "" },
            { "TRYK_U_B_AOR2_OD_CombatUniform", "", 350, "" },
            { "TRYK_U_B_BLKOCP_CombatUniform", "", 350, "" },
            { "TRYK_U_B_BLKTAN_CombatUniform", "", 350, "" },
            { "TRYK_U_B_BLTAN_T", "", 350, "" },
            { "TRYK_U_B_C01_Tsirt", "", 350, "" },
            { "TRYK_U_B_BLK3CD_Tshirt", "", 350, "" },
            { "TRYK_U_B_BLKTAN", "", 350, "" },
            { "TRYK_U_B_BLK_OD", "", 350, "" },
            { "TRYK_U_B_OD_BLK", "", 350, "" },
            { "TRYK_U_B_ODTAN", "", 350, "" },
            { "TRYK_U_B_BLK_TAN_2", "", 350, "" },
            { "TRYK_U_B_3CD_BLK_BDUTshirt2", "", 350, "" },
            { "TRYK_U_B_GRYOCP_CombatUniform", "", 350, "" },
            { "TRYK_OVERALL_SAGE_BLKboots_nk_blk2", "", 350, "" },
            { "TRYK_OVERALL_nok_flesh", "", 350, "" },
            { "TRYK_U_B_ODTANR_CombatUniformTshirt", "", 350, "" },
            { "TRYK_U_Bts_UCP_PCUs", "", 350, "" },
            { "TRYK_U_Bts_GRYGRY_PCUs", "", 350, "" },
            { "TRYK_U_B_PCUHs", "", 350, "" },
            { "TRYK_U_B_PCUODHs", "", 350, "" },
            { "TRYK_U_B_PCUGs_BLK_R", "", 350, "" },
            { "TRYK_U_B_PCUs_R", "", 350, "" },
            { "TRYK_U_B_BLK_tan_Rollup_CombatUniform", "", 350, "" },
            { "TRYK_U_B_wh_blk_Rollup_CombatUniform", "", 350, "" },
            { "TRYK_U_B_wh_OD_Rollup_CombatUniform", "", 350, "" },
            { "TRYK_U_B_wh_tan_Rollup_CombatUniform", "", 350, "" },

            { "TRYK_shirts_DENIM_ylb", "", 150, "" },
            { "TRYK_shirts_DENIM_BK_Sleeve", "", 150, "" },
            { "TRYK_shirts_DENIM_BWH_Sleeve", "", 150, "" },
            { "TRYK_shirts_DENIM_R_Sleeve", "", 150, "" },
            { "TRYK_shirts_DENIM_RED2_Sleeve", "", 150, "" },
            { "TRYK_shirts_TAN_PAD_BK", "", 150, "" },
            { "TRYK_shirts_BLK_PAD_BL", "", 150, "" },
            { "TRYK_shirts_PAD_BLW", "", 150, "" },
            { "TRYK_shirts_PAD", "", 150, "" },
            { "TRYK_hoodie_FR", "", 150, "" },
            { "TRYK_U_hood_mc", "", 150, "" },
            { "TRYK_U_pad_j_blk", "", 150, "" },
            { "TRYK_U_denim_jersey_blu", "", 150, "" },

            { "TRYK_U_taki_BL", "", 400, "" },
            { "TRYK_U_taki_BLK", "", 400, "" },
            { "TRYK_U_taki_COY", "", 400, "" },
            { "TRYK_U_taki_wh", "", 400, "" },
            { "TRYK_ZARATAKI", "", 400, "" },
            { "TRYK_ZARATAKI2", "", 400, "" },
            { "TRYK_ZARATAKI3", "", 400, "" },
            { "U_O_Wetsuit", "", 1750, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "Gorb_KnittedHat2", "", 30, "" },
            { "Gorb_KnittedHat1", "", 30, "" },
            { "Gorb_KnittedHat3", "", 30, "" },
            { "Gorb_KnittedHat4", "", 30, "" },
            { "Gorb_MrsClaus1", "", 30, "" },
            { "Gorb_MrsClaus3", "", 30, "" },
            { "ALE_H_NewEra_Redsox", "", 30, "" },
            { "ALE_H_NewEra_Black", "", 30, "" },
            { "ALE_H_NewEra_Lakers", "", 30, "" },
            { "Kio_No1_Hat", "", 30, "" },
            { "Gorb_Penguin", "", 30, "" },
            { "Kio_Pirate_Hat", "", 30, "" },
            { "Gorb_Reindeer", "", 30, "" },
            { "Gorb_RoughSantaClaus1", "", 30, "" },
            { "H_ALFR_Samurai_Mask", "", 30, "" },
            { "Gorb_SantaHat", "", 30, "" },
            { "Gorb_TreeMask1", "", 30, "" },
            { "turban", "", 30, "" },
            { "Gorb_TurkeyMask1", "", 30, "" },
            { "Gorb_UglyMrsClaus1", "", 30, "" },
            { "Kio_Hat", "", 30, "" },
            { "H_Capbw_pmc", "", 30, "" },
            { "Kio_Afro_Hat", "", 30, "" },
            { "Gorb_AngryGingerbread3", "", 30, "" },
            { "kio_vfv_mask", "", 30, "" },
            { "Kio_Capital_Hat", "", 30, "" },
            { "Gorb_PuddingHat", "", 30, "" },
            { "ALE_H_Cowboy_Black", "", 30, "" },
            { "EF_FBNE_BL", "", 30, "" },
            { "Gorb_FestiveHat1", "", 30, "" },
            { "kio_skl_msk_GOW", "", 30, "" },
            { "H_ALFR_Metal_Facemask_gry", "", 30, "" },
            { "H_ALFR_Metal_Facemask_oli", "", 30, "" },
            { "H_ALFR_Metal_Facemask_sand", "", 30, "" },
            { "H_ALFR_Metal_Facemask_blk", "", 30, "" },
            { "H_MilCap_oucamo", "", 50, "" },
            { "H_MilCap_gen_F", "", 40, "" },
            { "H_MilCap_tna_F", "", 40, "" },
            { "H_Beret_gen_F", "", 200, "" },
            { "H_Bandanna_mcamo", "", 25, "" },
            { "H_Bandanna_camo", "", 25, "" },
            { "H_Booniehat_mcamo", "Booniehat (MTP)", 50, "" },
            { "H_Booniehat_indp", " Booniehat (Khaki)", 50, "" },
            { "H_Booniehat_tna_F", "Booniehat (Tropic)", 50, "" },
            { "H_TurbanO_blk", "Black Turban", 100, "" },
            { "H_Hat_camo", "", 100, "" },
            { "H_HelmetO_ocamo", "", 150, "" },
            { "H_HelmetO_ghex_F", "", 150, "" },
            { "H_HelmetB_light", "", 150, "" },
            { "H_HelmetB_light_desert", "", 150, "" },
            { "H_HelmetB_light_grass", "", 150, "" },
            { "H_HelmetB_light_sand", "", 150, "" },
            { "H_HelmetB_light_snakeskin", "", 200, "" },
            { "H_HelmetB_Light_tna_F", "", 200, "" },
            { "H_HelmetB_Enh_tna_F", "", 200, "" },
            { "H_HelmetB_paint", "", 200, "" },
            { "H_HelmetB_plain_mcamo", "", 200, "" },
            { "H_HelmetB_tna_F", "", 200, "" },
            { "H_HelmetIA_net", "", 200, "" },
            { "H_HelmetSpecO_ocamo", "", 200, "" },
            { "H_Shemag_tan", "", 125, "" },
            { "H_Shemag_olive_hs", "", 125, "" },
            { "H_ShemagOpen_tan", "", 125, "" },
            { "H_Shemag_olive", "", 125, "" },
            { "H_HelmetCrew_O_ghex_F", "", 300, "" },
            { "H_HelmetB_TI_tna_F", "", 300, "" },
            { "TRYK_H_PASGT_BLK", "", 1000, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "G_Shades_Black", "", 20, "" },
            { "G_Shades_Blue", "", 20, "" },
            { "G_Sport_Blackred", "", 25, "" },
            { "G_Sport_Checkered", "", 25, "" },
            { "G_Sport_Blackyellow", "", 25, "" },
            { "G_Sport_BlackWhite", "", 25, "" },
            { "G_Lowprofile", "", 30, "" },
            { "G_Squares", "", 50, "" },
            { "G_Combat", "", 25, "" },
            { "G_Balaclava_blk", "", 15, "" },
            { "G_Balaclava_combat", "", 15, "" },
            { "G_Balaclava_lowprofile", "", 15, "" },
            { "G_Balaclava_oli", "", 15, "" },
            { "G_Bandanna_aviator", "", 15, "" },
            { "G_Bandanna_beast", "", 15, "" },
            { "G_Bandanna_blk", "", 15, "" },
            { "G_Bandanna_khk", "", 15, "" },
            { "G_Bandanna_oli", "", 15, "" },
            { "G_Bandanna_shades", "", 15, "" },
            { "G_Bandanna_sport", "", 15, "" },
            { "G_Bandanna_tan", "", 15, "" },
            { "Mask_M50", "Gasmask", 1000, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
            { "V_Chestrig_khk", "", 300, "" },
            { "V_TacVest_brn", "", 1550, "" },
            { "V_TacVest_camo", "", 1550, "" },
            { "V_TacVest_khk", "", 1550, "" },
            { "V_TacVest_oli", "", 1550, "" },
            { "V_PlateCarrierIA1_dgtl", "", 3650, "" },
            { "V_PlateCarrier2_rgr", "", 4450, "" },
            { "VSM_FAPC_Operator_AOR1", "", 4650, "" },
            { "VSM_LBT6094_MG_AOR1", "", 6450, "" },
            { "VSM_RAV_operator_M81", "", 6450, "" },
            { "VSM_RAV_MG_AOR1", "", 6850, "" },
            { "VSM_RAV_Breacher_M81", "", 6850, "" },
            { "VSM_RAV_MG_OGA_OD", "", 6850, "" }

        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "B_OutdoorPack_blk", "", 500, "" },
            { "B_AssaultPack_khk", "", 200, "" },
            { "B_AssaultPack_dgtl", "", 200, "" },
            { "B_AssaultPack_rgr", "", 200, "" },
            { "B_AssaultPack_sgg", "", 200, "" },
            { "B_AssaultPack_blk", "", 200, "" },
            { "B_AssaultPack_cbr", "", 200, "" },
            { "B_AssaultPack_mcamo", "", 200, "" },
            { "B_TacticalPack_oli", "", 250, "" },
            { "B_Kitbag_mcamo", "", 300, "" },
            { "B_Kitbag_sgg", "", 300, "" },
            { "B_Kitbag_cbr", "", 300, "" },
            { "B_FieldPack_blk", "", 500, "" },
            { "B_FieldPack_ocamo", "", 500, "" },
            { "B_FieldPack_oucamo", "", 500, "" },
            { "B_Bergen_sgg", "", 650, "" },
            { "B_Bergen_mcamo", "", 650, "" },
            { "B_Bergen_rgr", "", 650, "" },
            { "B_Bergen_blk", "", 650, "" },
            { "B_Carryall_ocamo", "", 750, "" },
            { "B_Carryall_oucamo", "", 750, "" },
            { "B_Carryall_mcamo", "", 750, "" },
            { "B_Carryall_oli", "", 750, "" },
            { "B_Carryall_khk", "", 750, "" },
            { "B_Carryall_cbr", "", 750, "" },
            { "B_Bergen_dgtl_f", "", 1650, "" },
            { "B_Bergen_tna_f", "", 1650, "" },
            { "cg_invisbp", "", 800, "" }
        };
    };

    class kart {
        title = "STR_Shops_C_Kart";
        conditions = "";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_C_Driver_1_black", "", 1500, "" },
            { "U_C_Driver_1_blue", "", 1500, "" },
            { "U_C_Driver_1_red", "", 1500, "" },
            { "U_C_Driver_1_orange", "", 1500, "" },
            { "U_C_Driver_1_green", "", 1500, "" },
            { "U_C_Driver_1_white", "", 1500, "" },
            { "U_C_Driver_1_yellow", "", 1500, "" },
            { "U_C_Driver_2", "", 3500, "" },
            { "U_C_Driver_1", "", 3600, "" },
            { "U_C_Driver_3", "", 3700, "" },
            { "U_C_Driver_4", "", 3700, "" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "H_RacingHelmet_1_black_F", "", 1000, "" },
            { "H_RacingHelmet_1_red_F", "", 1000, "" },
            { "H_RacingHelmet_1_white_F", "", 1000, "" },
            { "H_RacingHelmet_1_blue_F", "", 1000, "" },
            { "H_RacingHelmet_1_yellow_F", "", 1000, "" },
            { "H_RacingHelmet_1_green_F", "", 1000, "" },
            { "H_RacingHelmet_1_F", "", 2500, "" },
            { "H_RacingHelmet_2_F", "", 2500, "" },
            { "H_RacingHelmet_3_F", "", 2500, "" },
            { "H_RacingHelmet_4_F", "", 2500, "" }
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" }
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" }
        };
    };

    class GangClothing {
        title = "Gang Clothing";
        conditions = "call(life_gangLevel) > 0";
        side = "civ";
        uniforms[] = {
            { "NONE", $STR_C_Remove_uniforms, 0, "" },
        };
        goggles[] = {
            { "NONE", $STR_C_Remove_goggles, 0, "" },
            { "Mask_M50", "Gasmask", 150, "call(life_gangLevel) isEqualTo 15 || call(life_gangLevel) isEqualTo 19 || call(life_gangLevel) isEqualTo 21" },
            { "d3s_Glasses_scarf_c", "", 100, "call(life_gangLevel) isEqualTo 19" },
            { "CPE_MK50", "", 100, "call(life_gangLevel) isEqualTo 19" },
            { "jamie_blackhelmet", "", 100, "call(life_gangLevel) isEqualTo 19" },
            { "G_Bandanna_aviator", "", 100, "call(life_gangLevel) isEqualTo 19" }
        };
        headgear[] = {
            { "NONE", $STR_C_Remove_headgear, 0, "" },
            { "TLA_Beret_Lieutenant", "", 100, "call(life_gangLevel) isEqualTo 5" }
        };
        vests[] = {
            { "NONE", $STR_C_Remove_vests, 0, "" },
        };
        backpacks[] = {
            { "NONE", $STR_C_Remove_backpacks, 0, "" },
            { "cg_invisbp", "Invisable Backpack", 800, "" }
        };
    };
};
